# Generated by Django 5.1.4 on 2025-05-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название темы (например, Python, Golang и т.д.)', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Описание темы', null=True)),
                ('icon', models.CharField(default='/static/blog/images/icons/default-icon.png', help_text='Путь к иконке темы (например, blog/images/icons/java-icon.png)', max_length=255)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'topics',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='topics_name_5f3c7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название подтемы', max_length=255)),
                ('topic', models.ForeignKey(help_text='Родительская тема', on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Подтема',
                'verbose_name_plural': 'Подтемы',
                'db_table': 'subtopics',
                'ordering': ['topic', 'name'],
                'indexes': [models.Index(fields=['topic', 'name'], name='subtopics_topic_i_7d1938_idx')],
            },
        ),
    ]
