# Generated by Django 5.1.11 on 2025-10-15 14:53

import django.core.validators
import topics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Изображение или GIF для карточки темы (макс. 50 МБ). Поддерживаемые форматы: JPG, PNG, GIF', null=True, upload_to='topic_cards/images/', validators=[topics.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='topic',
            name='card_video',
            field=models.FileField(blank=True, help_text='Видео для карточки темы (макс. 50 МБ). Поддерживаемые форматы: MP4, WEBM, MOV', null=True, upload_to='topic_cards/videos/', validators=[topics.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])]),
        ),
        migrations.AddField(
            model_name='topic',
            name='media_type',
            field=models.CharField(choices=[('default', 'По умолчанию (иконка или picsum)'), ('image', 'Изображение/GIF'), ('video', 'Видео')], default='default', help_text='Тип медиа для отображения в карусели', max_length=20),
        ),
    ]
