# Generated by Django 5.1.4 on 2025-04-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(default='blog/images/icons/default-icon.png', help_text='Путь к иконке темы (например, blog/images/icons/java-icon.png)', max_length=255),
        ),
    ]
