# Generated by Django 5.1.11 on 2025-10-15 20:25

import django.core.validators
import topics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_card_image_topic_card_video_topic_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='Постер для видео (превью перед воспроизведением). Опционально. Поддерживаемые форматы: JPG, PNG', null=True, upload_to='topic_cards/posters/', validators=[topics.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='media_type',
            field=models.CharField(choices=[('default', 'По умолчанию (picsum.photos)'), ('image', 'Изображение/GIF'), ('video', 'Видео')], default='default', help_text='Тип медиа для отображения в карусели', max_length=20),
        ),
    ]
