# Generated by Django 5.1.11 on 2026-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0003_topic_video_poster_alter_topic_media_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subtopic",
            constraint=models.UniqueConstraint(
                fields=("topic", "name"), name="unique_subtopic_per_topic"
            ),
        ),
    ]
