# Generated by Django 5.1.11 on 2026-01-13 18:40

from django.db import migrations, models
from topics.utils import normalize_subtopic_name


def merge_duplicate_subtopics(apps, schema_editor):
    """
    Объединяет дубликаты подтем перед добавлением уникального ограничения.
    Выбирает каноническую подтему как ту, у которой больше всего задач.
    """
    Subtopic = apps.get_model('topics', 'Subtopic')
    Task = apps.get_model('tasks', 'Task')
    
    # Группируем подтемы по (topic_id, нормализованное название)
    grouped = {}
    for subtopic in Subtopic.objects.all():
        key = (subtopic.topic_id, normalize_subtopic_name(subtopic.name))
        grouped.setdefault(key, []).append(subtopic)
    
    # Обрабатываем только группы с дубликатами
    for (topic_id, normalized_name), items in grouped.items():
        if len(items) == 1:
            continue
        
        # Подсчитываем задачи для каждой подтемы
        items_with_counts = []
        for item in items:
            task_count = Task.objects.filter(subtopic_id=item.id).count()
            items_with_counts.append((item, task_count))
        
        # Выбираем каноническую (с наибольшим количеством задач, затем с наименьшим ID)
        canonical_item, _ = max(items_with_counts, key=lambda x: (x[1], -x[0].id))
        canonical = canonical_item
        
        # Нормализуем имя канонической подтемы
        if canonical.name != normalized_name:
            canonical.name = normalized_name
            canonical.save(update_fields=['name'])
        
        # Переносим задачи из дубликатов в каноническую и удаляем дубликаты
        for duplicate in items:
            if duplicate.id == canonical.id:
                continue
            
            # Переносим задачи
            Task.objects.filter(subtopic_id=duplicate.id).update(subtopic_id=canonical.id)
            # Удаляем дубликат
            duplicate.delete()


def reverse_merge_duplicate_subtopics(apps, schema_editor):
    """
    Обратная операция не требуется, так как мы только объединяем дубликаты.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0003_topic_video_poster_alter_topic_media_type"),
        ("tasks", "0001_initial"),  # Нужно для доступа к модели Task
    ]

    operations = [
        # Сначала объединяем дубликаты
        migrations.RunPython(merge_duplicate_subtopics, reverse_merge_duplicate_subtopics),
        # Затем добавляем уникальное ограничение
        migrations.AddConstraint(
            model_name="subtopic",
            constraint=models.UniqueConstraint(
                fields=("topic", "name"), name="unique_subtopic_per_topic"
            ),
        ),
    ]
