# Generated by Django 5.1.11 on 2026-04-12 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("topics", "0004_subtopic_unique_subtopic_per_topic"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="topic",
            name="topics_name_5f3c7a_idx",
        ),
        migrations.AddField(
            model_name="topic",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Тенант (инстанс платформы), которому принадлежит эта тема",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(
                help_text="Название темы (например, Python, Golang и т.д.)",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["tenant", "name"], name="topics_tenant__6725b1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_topic_name_per_tenant"
            ),
        ),
    ]
