# Generated by Django 5.1.11 on 2026-04-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_remove_topic_topics_name_5f3c7a_idx_topic_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Если указано, будет использоваться вместо стандартной иконки. Можно вставить SVG код целиком.', null=True, verbose_name='SVG код иконки'),
        ),
    ]
