# Generated by Django 5.1.11 on 2026-04-15 12:11

import django.core.validators
import topics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topic_icon_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Загрузите файл иконки (PNG, JPG или SVG). Используется, если не указан SVG код.', null=True, upload_to='topic_icons/', validators=[topics.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Файл иконки'),
        ),
    ]
