# Generated by Django 5.1.11 on 2026-05-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0008_topictranslation_subtopictranslation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subtopictranslation",
            new_name="subtopic_tr_languag_a911c7_idx",
            old_name="subtopic_tr_language_1883d3_idx",
        ),
        migrations.RenameIndex(
            model_name="topictranslation",
            new_name="topic_trans_languag_7f2765_idx",
            old_name="topic_transl_language_7e0b4b_idx",
        ),
    ]
