# Generated by Django 5.1.4 on 2025-01-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admin_is_active_admin_language_admin_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='language',
            field=models.CharField(default='ru', max_length=10),
        ),
    ]
