# Generated by Django 5.1.4 on 2025-01-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
