# Generated by Django 5.1.4 on 2025-05-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('platforms', '0004_alter_telegramgroup_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoadmin',
            name='is_super_admin',
        ),
        migrations.RemoveField(
            model_name='telegramadmin',
            name='is_super_admin',
        ),
        migrations.AlterField(
            model_name='djangoadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='djangoadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_permissions', related_query_name='%(app_label)s_%(class)s', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='telegramadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='telegramadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_permissions', related_query_name='%(app_label)s_%(class)s', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='telegramadmin',
            table='telegram_admins',
        ),
        migrations.CreateModel(
            name='TelegramAdminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to='accounts.telegramadmin')),
                ('telegram_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admins', to='platforms.telegramgroup', to_field='group_id')),
            ],
            options={
                'verbose_name': 'Связь Telegram Администратора и Группы',
                'verbose_name_plural': 'Связи Telegram Администраторов и Групп',
                'db_table': 'telegramadmin_groups',
                'unique_together': {('telegram_admin', 'telegram_group')},
            },
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
