# Generated by Django 5.1.4 on 2025-07-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_partial_unique_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь Сайта', 'verbose_name_plural': 'Пользователи Сайта'},
        ),
        migrations.AddField(
            model_name='userchannelsubscription',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки'),
        ),
        migrations.AddField(
            model_name='userchannelsubscription',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата разблокировки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит пользователь.', to='auth.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Индивидуальные разрешения пользователя.', to='auth.permission', verbose_name='Разрешения'),
        ),
        migrations.AlterField(
            model_name='djangoadmin',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='userchannelsubscription',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('banned', 'Заблокирована')], default='inactive', max_length=20, verbose_name='Статус подписки'),
        ),
        migrations.CreateModel(
            name='MiniAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='@username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('avatar', models.URLField(blank=True, max_length=500, null=True, verbose_name='Аватар (URL фото из Telegram)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний визит')),
                ('django_admin', models.OneToOneField(blank=True, help_text='Связь с Django админом, если он также управляет сайтом', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_app_user', to='accounts.djangoadmin', verbose_name='Django админ')),
                ('telegram_admin', models.OneToOneField(blank=True, help_text='Связь с админом Telegram бота, если он также является админом', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_app_user', to='accounts.telegramadmin', verbose_name='Админ бота')),
                ('telegram_user', models.OneToOneField(blank=True, help_text='Связь с пользователем Telegram бота, если он также использует бота', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_app_user', to='accounts.telegramuser', verbose_name='Пользователь бота')),
            ],
            options={
                'verbose_name': 'Mini App Пользователь',
                'verbose_name_plural': 'Mini App Пользователи',
                'db_table': 'mini_app_users',
                'indexes': [models.Index(fields=['telegram_id'], name='mini_app_us_telegra_9830d4_idx'), models.Index(fields=['username'], name='mini_app_us_usernam_26ef13_idx'), models.Index(fields=['created_at'], name='mini_app_us_created_fceab0_idx'), models.Index(fields=['last_seen'], name='mini_app_us_last_se_66bd16_idx')],
            },
        ),
    ]
