# Generated by Django 5.1.4 on 2025-07-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_partial_unique_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='@username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний визит')),
                ('django_admin', models.OneToOneField(blank=True, help_text='Связь с Django админом, если он также управляет сайтом', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_app_user', to='accounts.djangoadmin', verbose_name='Django админ')),
                ('telegram_admin', models.OneToOneField(blank=True, help_text='Связь с админом Telegram бота, если он также является админом', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_app_user', to='accounts.telegramadmin', verbose_name='Админ бота')),
                ('telegram_user', models.OneToOneField(blank=True, help_text='Связь с пользователем Telegram бота, если он также использует бота', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_app_user', to='accounts.telegramuser', verbose_name='Пользователь бота')),
            ],
            options={
                'verbose_name': 'Mini App Пользователь',
                'verbose_name_plural': 'Mini App Пользователи',
                'db_table': 'mini_app_users',
                'indexes': [models.Index(fields=['telegram_id'], name='mini_app_us_telegra_9830d4_idx'), models.Index(fields=['username'], name='mini_app_us_usernam_26ef13_idx'), models.Index(fields=['created_at'], name='mini_app_us_created_fceab0_idx'), models.Index(fields=['last_seen'], name='mini_app_us_last_se_66bd16_idx')],
            },
        ),
    ]
