# Generated by Django 5.1.4 on 2025-07-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_miniappuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannelsubscription',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки'),
        ),
        migrations.AddField(
            model_name='userchannelsubscription',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата разблокировки'),
        ),
        migrations.AlterField(
            model_name='userchannelsubscription',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('banned', 'Заблокирована')], default='inactive', max_length=20, verbose_name='Статус подписки'),
        ),
    ]
