# Generated by Django 5.1.4 on 2025-09-04 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniappuser',
            name='linked_custom_user',
            field=models.OneToOneField(blank=True, help_text='Связь с основным пользователем сайта, если он существует', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_app_profile', to=settings.AUTH_USER_MODEL, verbose_name='Связанный пользователь сайта'),
        ),
        migrations.AlterField(
            model_name='miniappuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='mini_app_avatars/', verbose_name='Аватар Mini App'),
        ),
    ]
