# Generated by Django 5.1.4 on 2025-07-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniappuser',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Аватар (URL фото из Telegram)'),
        ),
    ]
