# Generated by Django 5.1.4 on 2025-02-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_facebook_profile_github_profile_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram_username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
