# Generated by Django 5.1.4 on 2025-09-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_miniappuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniappuser',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Аватар (URL фото из Telegram)'),
        ),
    ]
