# Generated by Django 5.1.4 on 2025-09-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_miniappuser_linked_custom_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniappuser',
            name='telegram_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL фото из Telegram'),
        ),
    ]
