# Generated by Django 5.1.11 on 2025-09-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_telegram_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniappuser',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='miniappuser',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='miniappuser',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='miniappuser',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='miniappuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='miniappuser',
            name='website',
            field=models.URLField(blank=True, verbose_name='Веб-сайт'),
        ),
        migrations.AddField(
            model_name='miniappuser',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
