# Generated by Django 5.1.4 on 2025-05-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fix_telegram_admins_nullable'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('platforms', '0004_alter_telegramgroup_topic_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='telegramadmin',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='djangoadmin',
            name='is_telegram_admin',
        ),
        migrations.AddField(
            model_name='telegramadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='telegram_admins', through='accounts.TelegramAdminGroup', to='platforms.telegramgroup', verbose_name='Telegram Группа/Канал'),
        ),
        migrations.AlterField(
            model_name='djangoadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='djangoadmin',
            name='is_django_admin',
            field=models.BooleanField(default=True, verbose_name='Django Admin'),
        ),
        migrations.AlterField(
            model_name='djangoadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='telegramadmin',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
