# Generated by Django 5.1.11 on 2025-09-23 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_miniappuser_facebook_miniappuser_github_and_more'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniappuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='miniappuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='miniappuser',
            name='programming_language',
            field=models.ForeignKey(blank=True, help_text='Ссылка на тему (язык программирования) из базы тем', null=True, on_delete=django.db.models.deletion.SET_NULL, to='topics.topic', verbose_name='Любимый язык программирования'),
        ),
    ]
