# Generated by Django 5.1.11 on 2025-09-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_miniappuser_birth_date_miniappuser_gender_and_more'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniappuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], help_text='Уровень разработчика', max_length=20, null=True, verbose_name='Грейд'),
        ),
        migrations.AddField(
            model_name='miniappuser',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, help_text='Множественный выбор технологий, которые изучает пользователь', related_name='mini_app_users', to='topics.topic', verbose_name='Любимые технологии'),
        ),
    ]
