# Generated by Django 5.1.4 on 2025-05-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_djangoadmin_is_telegram_admin'),
        ('platforms', '0004_alter_telegramgroup_topic_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userchannelsubscription',
            name='unique_user_channel',
        ),
        migrations.RemoveField(
            model_name='userchannelsubscription',
            name='user',
        ),
        migrations.AlterField(
            model_name='userchannelsubscription',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_subscriptions', to='accounts.telegramuser', verbose_name='Telegram пользователь'),
        ),
        migrations.AddConstraint(
            model_name='userchannelsubscription',
            constraint=models.UniqueConstraint(fields=('telegram_user', 'channel'), name='unique_telegram_user_channel'),
        ),
    ]
