# Generated by Django 5.1.11 on 2025-10-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_miniappuser_grade_miniappuser_programming_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniappuser',
            name='is_profile_public',
            field=models.BooleanField(default=True, help_text='Определяет, доступен ли профиль для просмотра другим пользователям', verbose_name='Публичный профиль'),
        ),
    ]
