# Generated by Django 5.1.4 on 2025-05-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userchannelsubscription_unique_user_channel_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE telegram_users DROP CONSTRAINT telegram_users_linked_user_id_key;',
            reverse_sql='ALTER TABLE telegram_users ADD CONSTRAINT telegram_users_linked_user_id_key UNIQUE (linked_user_id);'
        ),
    ]
