# Generated by Django 5.1.4 on 2025-02-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_usersettings_dark_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
