# Generated by Django 5.1.11 on 2025-10-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_miniappuser_is_profile_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Поддерживаются изображения и GIF файлы",
                        upload_to="mini_app_avatars/",
                        verbose_name="Изображение аватарки",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Порядок отображения в галерее (0, 1, 2)",
                        verbose_name="Порядок отображения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatars",
                        to="accounts.miniappuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аватарка пользователя",
                "verbose_name_plural": "Аватарки пользователей",
                "db_table": "user_avatars",
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=["user", "order"], name="user_avatar_user_id_337ea5_idx"
                    )
                ],
                "unique_together": {("user", "order")},
            },
        ),
    ]
