# Generated by Django 5.1.4 on 2025-05-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250512_1601'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE telegram_users ALTER COLUMN created_at SET DEFAULT NOW();',
            reverse_sql='ALTER TABLE telegram_users ALTER COLUMN created_at DROP DEFAULT;'
        ),
    ]
