# Generated by Django 5.1.4 on 2025-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_djangoadmin_is_super_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoadmin',
            name='is_super_admin',
            field=models.BooleanField(default=False, verbose_name='Super Admin'),
        ),
        migrations.AlterField(
            model_name='djangoadmin',
            name='is_telegram_admin',
            field=models.BooleanField(default=False, verbose_name='Telegram Admin'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='is_super_admin',
            field=models.BooleanField(default=False, verbose_name='Super Admin'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='is_telegram_admin',
            field=models.BooleanField(default=False, verbose_name='Telegram Admin'),
        ),
        migrations.AlterField(
            model_name='telegramadmin',
            name='is_super_admin',
            field=models.BooleanField(default=False, verbose_name='Super Admin'),
        ),
        migrations.AlterField(
            model_name='telegramadmin',
            name='is_telegram_admin',
            field=models.BooleanField(default=False, verbose_name='Telegram Admin'),
        ),
    ]
