# Generated by Django 5.1.11 on 2025-11-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_useravatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="miniappuser",
            name="notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Общий переключатель всех уведомлений",
                verbose_name="Уведомления включены",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_telegram_id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="ID получателя уведомления в Telegram",
                        verbose_name="Telegram ID получателя",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "Новое сообщение"),
                            ("comment_reply", "Ответ на комментарий"),
                            ("report", "Жалоба на комментарий"),
                            ("subscription", "Новая подписка"),
                            ("comment", "Новый комментарий"),
                            ("other", "Другое"),
                        ],
                        help_text="Тип события, вызвавшего уведомление",
                        max_length=20,
                        verbose_name="Тип уведомления",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Краткий заголовок уведомления",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Полный текст уведомления", verbose_name="Сообщение"
                    ),
                ),
                (
                    "related_object_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID объекта, с которым связано уведомление",
                        null=True,
                        verbose_name="ID связанного объекта",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("message", "Сообщение"),
                            ("comment", "Комментарий"),
                            ("report", "Жалоба"),
                            ("subscription", "Подписка"),
                        ],
                        help_text="Тип объекта (message, comment, report, subscription)",
                        max_length=20,
                        null=True,
                        verbose_name="Тип связанного объекта",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Отметка о прочтении уведомления",
                        verbose_name="Прочитано",
                    ),
                ),
                (
                    "sent_to_telegram",
                    models.BooleanField(
                        default=False,
                        help_text="Отметка об отправке уведомления в Telegram",
                        verbose_name="Отправлено в Telegram",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Время создания уведомления",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_telegram_id", "-created_at"],
                        name="notificatio_recipie_03c650_idx",
                    ),
                    models.Index(
                        fields=["recipient_telegram_id", "is_read"],
                        name="notificatio_recipie_f0481c_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_19df93_idx",
                    ),
                ],
            },
        ),
    ]
