# Generated by Django 5.1.11 on 2025-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_admin_notification",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Если True, уведомление предназначено всем админам (recipient_telegram_id должен быть NULL)",
                verbose_name="Уведомление для админов",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient_telegram_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="ID получателя уведомления в Telegram. NULL для админских уведомлений (всем админам)",
                null=True,
                verbose_name="Telegram ID получателя",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_admin_notification", "-created_at"],
                name="notificatio_is_admi_9eb268_idx",
            ),
        ),
    ]
