# Generated by Django 5.1.11 on 2025-11-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_notification_is_admin_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="miniappuser",
            name="ban_reason",
            field=models.TextField(
                blank=True,
                help_text="Описание причины блокировки пользователя",
                null=True,
                verbose_name="Причина блокировки",
            ),
        ),
        migrations.AddField(
            model_name="miniappuser",
            name="banned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда пользователь был заблокирован",
                null=True,
                verbose_name="Дата блокировки",
            ),
        ),
        migrations.AddField(
            model_name="miniappuser",
            name="banned_by_admin_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Telegram ID администратора, который заблокировал пользователя",
                null=True,
                verbose_name="ID админа, заблокировавшего",
            ),
        ),
        migrations.AddField(
            model_name="miniappuser",
            name="banned_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата окончания блокировки (None = перманентный бан)",
                null=True,
                verbose_name="Заблокирован до",
            ),
        ),
        migrations.AddField(
            model_name="miniappuser",
            name="is_banned",
            field=models.BooleanField(
                default=False,
                help_text="Заблокирован ли пользователь за нарушения",
                verbose_name="Заблокирован",
            ),
        ),
    ]
