# Generated by Django 5.1.4 on 2025-02-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoadmin',
            name='is_telegram_admin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Telegram Admin'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='is_telegram_admin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Telegram Admin'),
        ),
        migrations.AlterField(
            model_name='telegramadmin',
            name='is_telegram_admin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Telegram Admin'),
        ),
    ]
