# Generated by Django 5.1.11 on 2025-11-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_miniappuser_ban_reason_miniappuser_banned_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("message", "Новое сообщение"),
                    ("comment_reply", "Ответ на комментарий"),
                    ("report", "Жалоба на комментарий"),
                    ("subscription", "Новая подписка"),
                    ("comment", "Новый комментарий"),
                    ("donation", "Новый донат"),
                    ("feedback", "Обратная связь"),
                    ("other", "Другое"),
                ],
                help_text="Тип события, вызвавшего уведомление",
                max_length=20,
                verbose_name="Тип уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_object_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("message", "Сообщение"),
                    ("comment", "Комментарий"),
                    ("report", "Жалоба"),
                    ("subscription", "Подписка"),
                    ("donation", "Донат"),
                    ("feedback", "Обратная связь"),
                ],
                help_text="Тип объекта (message, comment, report, subscription)",
                max_length=20,
                null=True,
                verbose_name="Тип связанного объекта",
            ),
        ),
    ]
