# Generated by Django 5.1.11 on 2026-04-12 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_notification_notification_type_and_more"),
        ("tenants", "0001_initial"),
        ("topics", "0004_subtopic_unique_subtopic_per_topic"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="miniappuser",
            name="mini_app_us_telegra_9830d4_idx",
        ),
        migrations.AddField(
            model_name="customuser",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Тенант пользователя. None = superuser (видит все).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="web_users",
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="miniappuser",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Тенант, к которому привязан пользователь Mini App",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mini_app_users",
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="telegramadmin",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Тенант, к которому привязан этот Telegram-админ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_admins",
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Тенант, к которому привязан этот Telegram-пользователь",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_users",
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AlterField(
            model_name="miniappuser",
            name="telegram_id",
            field=models.BigIntegerField(db_index=True, verbose_name="Telegram ID"),
        ),
        migrations.AlterField(
            model_name="telegramadmin",
            name="telegram_id",
            field=models.BigIntegerField(db_index=True, verbose_name="Telegram ID"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="telegram_id",
            field=models.BigIntegerField(db_index=True, verbose_name="Telegram ID"),
        ),
        migrations.AddIndex(
            model_name="miniappuser",
            index=models.Index(
                fields=["tenant", "telegram_id"], name="mini_app_us_tenant__108a11_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="miniappuser",
            constraint=models.UniqueConstraint(
                fields=("tenant", "telegram_id"), name="unique_mini_app_user_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="telegramuser",
            constraint=models.UniqueConstraint(
                fields=("tenant", "telegram_id"), name="unique_telegram_user_per_tenant"
            ),
        ),
    ]
