# Generated by Django 5.1.11 on 2026-04-15 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_miniappuser_mini_app_us_telegra_9830d4_idx_and_more"),
        ("tenants", "0002_tenant_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Тенант, к которому привязано уведомление (опционально для глобальных)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
    ]
