# Generated by Django 5.1.4 on 2025-07-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_miniappuser'),
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='django_admin',
            field=models.OneToOneField(blank=True, help_text='Связь с Django админом, если он также управляет сайтом', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_account', to='accounts.djangoadmin', verbose_name='Django админ'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='mini_app_user',
            field=models.OneToOneField(blank=True, help_text='Связь с пользователем Mini App, если он также использует Mini App', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_account', to='accounts.miniappuser', verbose_name='Mini App пользователь'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='telegram_admin',
            field=models.OneToOneField(blank=True, help_text='Связь с админом Telegram бота, если он также является админом', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_account', to='accounts.telegramadmin', verbose_name='Админ бота'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='telegram_user',
            field=models.OneToOneField(blank=True, help_text='Связь с пользователем Telegram бота, если он также использует бота', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_account', to='accounts.telegramuser', verbose_name='Пользователь бота'),
        ),
    ]
