"""
Сервис локализации для мини-приложения
"""
from typing import Dict, Any, Optional
from core.config import settings

class LocalizationService:
    """Сервис для управления переводами в мини-приложении"""
    
    # Словари переводов
    TRANSLATIONS = {
        "en": {
            # Навигация
            "home": "Home",
            "profile": "Profile", 
            "top_users": "Top Users",
            "statistics": "Statistics",
            "settings": "Settings",
            
            # Главная страница
            "search_placeholder": "Search topics...",
            "start_button": "Start",
            "back_button": "Back",
            "questions_count": "questions",
            "difficulty_easy": "Easy",
            "difficulty_medium": "Medium", 
            "difficulty_hard": "Hard",
            
            # Задачи
            "tasks": "Tasks",
            "task_image": "Task Image",
            "explanation": "Explanation",
            "no_tasks_available": "No tasks available",
            "correct_answer": "Correct Answer",
            "incorrect_answer": "Incorrect Answer",
            "correct_answer_message": "Correct! Great job!",
            "incorrect_answer_message": "Incorrect. Check the explanation below.",
            "dont_know_message": 'Correct! You chose "I don\'t know" - this is a good approach to learning.',
            "submitting_answer": "Submitting answer...",
            "already_answered": "You have already answered this question",
            "error_occurred": "An error occurred. Please try again.",
            "error_determine_user": "Error: failed to determine user",
            "network_error": "Network error. Check your connection.",
            
            # Комментарии
            "comments": "Comments",
            "add_comment": "Add a comment",
            "reply": "Reply",
            "reply_to": "in reply to",
            "reply_placeholder": "Write a reply...",
            "delete": "Delete",
            "report": "Report",
            "send": "Send",
            "photo": "Photo",
            "loading": "Loading",
            "loading_comments": "Loading comments",
            "error_loading_comments": "Error loading comments",
            "load_more": "Load more",
            "report_comment": "Report Comment",
            "report_reason_spam": "Spam",
            "report_reason_offensive": "Offensive content",
            "report_reason_inappropriate": "Inappropriate content",
            "report_reason_other": "Other",
            "report_description_placeholder": "Additional description (optional)",
            "no_comments_yet": "No comments yet. Be the first!",
            "comment_deleted": "[Comment deleted]",
            "confirm_delete_comment": "Are you sure you want to delete this comment?",
            "max_images_error": "Maximum 3 images",
            "min_text_error": "Comment must contain at least 3 characters",
            "comment_sent": "Comment sent",
            "report_sent": "Report sent. Thank you!",
            "report_already_sent": "You have already reported this comment",
            "reported": "Reported",
            "image_too_large": "Image is too large! Maximum: 5 MB. Current size:",
            "invalid_format": "Invalid format. Allowed: JPEG, PNG, GIF, WebP",
            
            # Профиль
            "profile_title": "Profile",
            "edit_profile": "Edit Profile",
            "save_changes": "Save Changes",
            "cancel": "Cancel",
            "upload_avatar": "Upload Avatar",
            "username": "Username",
            "first_name": "First Name",
            "last_name": "Last Name",
            "language": "Language",
            
            # Достижения
            "top_users_title": "Top Users",
            "top_5_title": "Top 5 Users",
            "all_users_title": "All Users",
            "show_all_users": "Show All Users",
            "hide_all_users": "Hide",
            "no_top_users": "No top users yet",
            "keep_playing": "Keep playing to get to the top!",
            
            # Фильтры
            "gender": "Gender",
            "age": "Age",
            "programming_language": "Programming Language",
            "rating": "Rating",
            "online_status": "Status",
            "online": "Online",
            "online_only": "Online only",
            "all": "All",
            "gender_placeholder": "Gender",
            "age_placeholder": "Age", 
            "technology_placeholder": "Technology",
            "male": "Male",
            "female": "Female",
            "reset_filters": "Reset ",
            
            # Статистика
            "statistics_title": "Statistics",
            "total_questions": "Total Questions",
            "correct_answers": "Correct Answers",
            "incorrect_answers": "Incorrect Answers",
            "accuracy": "Accuracy",
            "streak": "Current Streak",
            "best_streak": "Best Streak",
            "total_points": "Total Points",
            "topic_progress_title": "Topic Progress",
            "achievements_title": "Achievements",
            "no_statistics_data": "No data to display yet",
            "start_solving": "Start solving tasks to see statistics",
            "favorite_topic": "Favorite Topic",
            "not_defined": "Not defined",
            
            # Достижения
            "achievement_1": "First Step",
            "achievement_2": "Swift Expert", 
            "achievement_3": "Webmaster",
            "achievement_4": "Streak",
            "achievement_5": "Expert",
            "achievement_6": "Speed",
            
            
            # Настройки
            "settings_title": "Settings",
            "language_settings": "Language",
            "notifications": "Notifications",
            "dark_mode": "Dark Mode",
            "about": "About",
            "version": "Version",
            "share_app": "Share App",
            "share_app_description": "Share this app with friends",
            "qr_code": "QR Code",
            "copy_link": "Copy Link",
            "link_copied": "Link copied!",
            "app_description": "Educational quiz app for learning various topics",
            "share_social": "Share on Social Media",
            "app_name": "Quiz Mini App",
            "app_features_learning": "📚 Learning",
            "app_features_quizzes": "🎯 Quizzes",
            
            # Донаты
            "support_project": "Support Project",
            "donation_amount": "Donation Amount",
            "donation_currency": "Currency",
            "donate_button": "Donate",
            "donation_success": "Thank you for your support!",
            "donation_error": "Payment failed. Please try again.",
            "donation_processing": "Processing payment...",
            "donation_amount_placeholder": "Enter amount",
            "donation_name_placeholder": "Your name",
            "donation_email_placeholder": "Your email (optional)",
            "donation_description": "Support the development of this educational app",
            "donation_min_amount": "Minimum amount: $1",
            "donation_currency_usd": "USD ($)",
            "donation_currency_eur": "EUR (€)",
            "donation_currency_rub": "RUB (₽)",
            "donation_card_number": "Card Number",
            "donation_expiry": "MM/YY",
            "donation_cvc": "CVC",
            "donation_pay": "Pay",
            "donation_cancel": "Cancel",
            
            # Донаты - статусы и уведомления
            "donation_creating_payment": "Creating payment...",
            "donation_payment_ready": "Payment ready for processing",
            "donation_creation_error": "Payment creation error",
            "donation_network_error": "Network error",
            "donation_not_initialized": "Error: payment not initialized",
            "donation_processing": "Processing payment...",
            "donation_success_processed": "Payment successfully processed!",
            "donation_status": "Payment status",
            "donation_processing_error": "Payment processing error",
            "donation_saving_data": "Saving payment data...",
            "donation_saved_email_sent": "Payment saved! Thank you email sent to your email.",
            
            # Крипто-платежи
            "payment_method": "Payment Method",
            "card_payment": "Bank Card",
            "crypto_payment": "Cryptocurrency",
            "stars_payment": "Telegram Stars",
            "wallet_payment": "Telegram Wallet",
            "select_cryptocurrency": "Select Cryptocurrency",
            "waiting_for_payment": "Waiting for payment...",
            "payment_confirmed": "Payment confirmed!",
            "scan_qr_or_copy": "Scan QR code or copy address",
            "copy_address": "Copy Address",
            "address_copied": "Address copied!",
            "amount_to_send": "Amount to send",
            "payment_address": "Payment Address",
            "payment_expires": "Payment expires in",
            "checking_status": "Checking payment status...",
            "payment_received": "Payment received",
            "payment_pending": "Waiting for blockchain confirmation...",
            "payment_failed": "Payment failed",
            "payment_expired": "Payment expired",
            "usdt": "USDT (Tether)",
            "usdc": "USDC (USD Coin)",
            "busd": "BUSD (Binance USD)",
            "dai": "DAI (Dai Stablecoin)",
            "ton": "TON (Toncoin)",
            "btc": "BTC (Bitcoin)",
            "crypto_donation_created": "Crypto payment created successfully",
            "send_crypto_to_address": "Send cryptocurrency to the address below",
            "donation_partial_success": "Payment processed, but there were problems saving data.",
            "donation_payment_error": "Payment Error",
            "donation_payment_successful": "Payment Successful!",
            "donation_payment_processed": "Your payment has been successfully processed.",
            "donation_thanks_support": "Thank you for your support!",
            "donation_thanks_email": "Thank you email sent to your email.",
            "donation_warning": "Warning",
            "donation_enter_name": "Please enter your name",
            "donation_min_amount_error": "Minimum donation amount: $1",
            
            # Обратная связь
            "feedback_title": "Feedback",
            "feedback_description": "Report issues or suggest improvements",
            "feedback_category_bug": "🐛 Bug",
            "feedback_category_suggestion": "💡 Suggestion",
            "feedback_category_complaint": "😞 Complaint",
            "feedback_category_other": "📝 Other",
            "feedback_message_placeholder": "Describe your issue or suggestion...",
            "attach_images": "Attach Photos",
            "image_hint": "You can attach up to 3 photos (max 5MB each)",
            "send_feedback": "Send",
            "contact_admin": "Contact Admin",
            "feedback_error_category": "Please select a category",
            "feedback_error_short": "Message must be at least 3 characters",
            "feedback_sending": "Sending...",
            "feedback_success": "Thank you! Your message has been sent",
            "feedback_error": "Error sending message",
            "feedback_network_error": "Network error",
            "admin_contact_unavailable": "Admin contact unavailable",
            
            # Админ-панель
            "admin_analytics_title": "Admin Panel",
            "admin_analytics_subtitle": "Key metrics for mini app",
            "access_denied_title": "Access Denied",
            "access_denied_message": "This page is only accessible to administrators",
            "donations_title": "💰 Donations",
            "total_donations": "Total Donations",
            "total_amount": "Total Amount",
            "monthly_donations": "This Month",
            "monthly_amount": "Amount This Month",
            "by_source": "By Source",
            "source_website": "Website",
            "source_mini_app": "Mini App",
            "count": "Count",
            "amount": "Amount",
            "subscriptions_title": "👥 Subscribers",
            "total_users": "Total Users",
            "monthly_new_users": "New This Month",
            "weekly_new_users": "New This Week",
            "activity_title": "📊 Activity",
            "active_7_days": "Active (7 days)",
            "active_30_days": "Active (30 days)",
            "online_now": "Online Now",
            "last_updated": "Updated:",
            "analytics_load_error": "Error loading analytics",
            "admin_panel": "Admin Panel",
            
            # Общие
            "loading": "Loading...",
            "error": "Error",
            "success": "Success",
            "confirm": "Confirm",
            "delete": "Delete",
            "edit": "Edit",
            "close": "Close",
            "no_tasks_for_level": "No tasks for selected level",
            
            # Профиль - дополнительные
            "points": "Points",
            "rating": "Rating",
            "quizzes": "Quizzes",
            "success_rate": "Success Rate",
            "social_networks": "Social Networks",
            "no_social_links": "Social networks not specified.",
            "refresh_data": "Refresh Data",
            "refreshing_data": "Refreshing data...",
            "no_statistics_data": "No data available for display.",
            "profile_hidden": "Profile is hidden",
            "profile_hidden_message": "This user has hidden their profile",
            "write_message": "Write message",
            "viewing_profile": "Viewing profile",
            "profile_visibility": "Profile Visibility",
            "public_profile": "Public Profile",
            "private_profile": "Private Profile",
            "profile_visibility_description": "When enabled, other users can view your profile information",
            
            # Профессиональная информация
            "professional_info": "Professional Information",
            "grade": "Grade",
            "technologies": "Technologies",
            "grade_junior": "Junior",
            "grade_middle": "Middle",
            "grade_senior": "Senior",
            "not_specified": "Not specified",
            "no_technologies": "No technologies specified",
            "select_grade": "Select grade",
            "select_gender": "Select gender",
            "loading_technologies": "Loading technologies...",
            
            # Персональная информация
            "years_old": "years old",
            "age_unknown": "Age not specified",
            "grade_unknown": "Grade not specified",
            "junior": "Junior",
            "middle": "Middle",
            "senior": "Senior",
            "birth_date": "Birth Date",
            "gender_unknown": "Not specified",
        "website": "Website",
        "telegram": "Telegram",
        "github": "GitHub",
        "linkedin": "LinkedIn",
        "instagram": "Instagram",
        "facebook": "Facebook",
        "youtube": "YouTube",
        "select_technologies_optional": "Select technologies (optional)",
        "selected_technologies": "Selected:",
        "technologies": "technologies",
        "clear_all": "Clear all",
        "select_all": "Select all",
        "technologies_help": "Click on the list to select multiple technologies. The field can be left empty.",
        "share_topic": "Share Topic",
        "share_link_copied": "Share link copied!",
        "share_topic_with_friends": "Share this topic with your friends!",
        },
        "ru": {
            # Навигация
            "home": "Главная",
            "profile": "Профиль",
            "top_users": "Топ юзеров",
            "statistics": "Статистика",
            "settings": "Настройки",
            
            # Главная страница
            "search_placeholder": "Поиск тем...",
            "start_button": "Начать",
            "back_button": "Назад",
            "questions_count": "вопросов",
            "difficulty_easy": "Легкий",
            "difficulty_medium": "Средний",
            "difficulty_hard": "Сложный",
            
            # Задачи
            "tasks": "Задачи",
            "task_image": "Изображение задачи",
            "explanation": "Объяснение",
            "no_tasks_available": "Задачи не найдены",
            "correct_answer": "Правильный ответ",
            "incorrect_answer": "Неправильный ответ",
            "correct_answer_message": "Правильно! Отличная работа!",
            "incorrect_answer_message": "Неправильно. Посмотрите объяснение ниже.",
            "dont_know_message": 'Правильно! Вы выбрали "Не знаю" - это хороший подход к обучению.',
            "submitting_answer": "Отправляем ответ...",
            "already_answered": "Вы уже отвечали на этот вопрос",
            "error_occurred": "Произошла ошибка. Попробуйте еще раз.",
            "error_determine_user": "Ошибка: не удалось определить пользователя",
            "network_error": "Ошибка сети. Проверьте подключение.",
            
            # Комментарии
            "comments": "Комментарии",
            "add_comment": "Добавить комментарий",
            "reply": "Ответить",
            "reply_to": "в ответ",
            "reply_placeholder": "Напишите ответ...",
            "delete": "Удалить",
            "report": "Пожаловаться",
            "send": "Отправить",
            "photo": "Фото",
            "loading": "Загрузка",
            "loading_comments": "Загрузка комментариев",
            "error_loading_comments": "Ошибка загрузки комментариев",
            "load_more": "Загрузить ещё",
            "report_comment": "Пожаловаться на комментарий",
            "report_reason_spam": "Спам",
            "report_reason_offensive": "Оскорбительный контент",
            "report_reason_inappropriate": "Неуместный контент",
            "report_reason_other": "Другое",
            "report_description_placeholder": "Дополнительное описание (необязательно)",
            "no_comments_yet": "Комментариев пока нет. Будьте первым!",
            "comment_deleted": "[Комментарий удалён]",
            "confirm_delete_comment": "Вы уверены, что хотите удалить комментарий?",
            "max_images_error": "Максимум 3 изображения",
            "min_text_error": "Комментарий должен содержать минимум 3 символа",
            "comment_sent": "Комментарий отправлен",
            "report_sent": "Жалоба отправлена. Спасибо!",
            "report_already_sent": "Вы уже подали жалобу на этот комментарий",
            "reported": "Жалоба отправлена",
            "image_too_large": "Изображение слишком большое! Максимум: 5 MB. Текущий размер:",
            "invalid_format": "Недопустимый формат. Разрешены: JPEG, PNG, GIF, WebP",
            
            # Профиль
            "profile_title": "Профиль",
            "edit_profile": "Редактировать профиль",
            "save_changes": "Сохранить изменения",
            "cancel": "Отмена",
            "upload_avatar": "Загрузить аватар",
            "username": "Имя пользователя",
            "first_name": "Имя",
            "last_name": "Фамилия",
            "language": "Язык",
            
            # Достижения
            "top_users_title": "Топ юзеров",
            "top_5_title": "Топ-5 пользователей",
            "all_users_title": "Все пользователи",
            "show_all_users": "Все пользователи",
            "hide_all_users": "Скрыть",
            "no_top_users": "Пока нет лучших пользователей",
            "keep_playing": "Продолжайте играть, чтобы попасть в топ!",
            
            # Фильтры
            "gender": "Пол",
            "age": "Возраст",
            "programming_language": "Язык программирования",
            "rating": "Рейтинг",
            "online_status": "Статус",
            "online": "Онлайн",
            "online_only": "Только онлайн",
            "all": "Все",
            "gender_placeholder": "Пол",
            "age_placeholder": "Возраст",
            "technology_placeholder": "Тема",
            "male": "Мужской",
            "female": "Женский",
            "reset_filters": "Сбросить",
            
            # Статистика
            "statistics_title": "Статистика",
            "total_questions": "Всего вопросов",
            "correct_answers": "Правильных ответов",
            "incorrect_answers": "Неправильных ответов",
            "accuracy": "Точность",
            "streak": "Текущая серия",
            "best_streak": "Лучшая серия",
            "total_points": "Всего очков",
            "topic_progress_title": "Прогресс по темам",
            "achievements_title": "Достижения",
            "no_statistics_data": "Пока нет данных для отображения",
            "start_solving": "Начните решать задачи, чтобы увидеть статистику",
            "favorite_topic": "Любимая тема",
            "not_defined": "Не определена",
            
            # Достижения
            "achievement_1": "Первый шаг",
            "achievement_2": "Знаток Swift",
            "achievement_3": "Веб-мастер", 
            "achievement_4": "Серия",
            "achievement_5": "Эксперт",
            "achievement_6": "Скорость",
            
            
            # Настройки
            "settings_title": "Настройки",
            "language_settings": "Язык",
            "notifications": "Уведомления",
            "dark_mode": "Темная тема",
            "about": "О приложении",
            "version": "Версия",
            "share_app": "Поделиться приложением",
            "share_app_description": "Поделитесь приложением с друзьями",
            "qr_code": "QR-код",
            "copy_link": "Копировать ссылку",
            "link_copied": "Ссылка скопирована!",
            "app_description": "Образовательное приложение с квизами для изучения различных тем",
            "share_social": "Поделиться в соцсетях",
            "app_name": "Quiz Mini App",
            "app_features_learning": "📚 Обучение",
            "app_features_quizzes": "🎯 Квизы",
            
            # Донаты
            "support_project": "Поддержать проект",
            "donation_amount": "Сумма доната",
            "donation_currency": "Валюта",
            "donate_button": "Пожертвовать",
            "donation_success": "Спасибо за вашу поддержку!",
            "donation_error": "Ошибка платежа. Попробуйте еще раз.",
            "donation_processing": "Обработка платежа...",
            "donation_amount_placeholder": "Введите сумму",
            "donation_name_placeholder": "Ваше имя",
            "donation_email_placeholder": "Ваш email (необязательно)",
            "donation_description": "Поддержите разработку этого образовательного приложения",
            "donation_min_amount": "Минимальная сумма: $1",
            "donation_currency_usd": "USD ($)",
            "donation_currency_eur": "EUR (€)",
            "donation_currency_rub": "RUB (₽)",
            "donation_card_number": "Номер карты",
            "donation_expiry": "ММ/ГГ",
            "donation_cvc": "CVC",
            "donation_pay": "Оплатить",
            "donation_cancel": "Отмена",
            
            # Донаты - статусы и уведомления
            "donation_creating_payment": "Создание платежа...",
            "donation_payment_ready": "Платеж готов к обработке",
            "donation_creation_error": "Ошибка создания платежа",
            "donation_network_error": "Ошибка сети",
            "donation_not_initialized": "Ошибка: платеж не инициализирован",
            "donation_processing": "Обработка платежа...",
            "donation_success_processed": "Платеж успешно обработан!",
            "donation_status": "Статус платежа",
            "donation_processing_error": "Ошибка обработки платежа",
            "donation_saving_data": "Сохранение данных платежа...",
            "donation_saved_email_sent": "Платеж сохранен! Благодарственное письмо отправлено на ваш email.",
            
            # Крипто-платежи
            "payment_method": "Способ оплаты",
            "card_payment": "Банковская карта",
            "crypto_payment": "Криптовалюта",
            "stars_payment": "Telegram Stars",
            "wallet_payment": "Telegram Wallet",
            "select_cryptocurrency": "Выберите криптовалюту",
            "waiting_for_payment": "Ожидание оплаты...",
            "payment_confirmed": "Оплата подтверждена!",
            "scan_qr_or_copy": "Отсканируйте QR-код или скопируйте адрес",
            "copy_address": "Копировать адрес",
            "address_copied": "Адрес скопирован!",
            "amount_to_send": "Сумма к отправке",
            "payment_address": "Адрес для оплаты",
            "payment_expires": "Платеж истекает через",
            "checking_status": "Проверка статуса платежа...",
            "payment_received": "Платеж получен",
            "payment_pending": "Ожидание подтверждения в блокчейне...",
            "payment_failed": "Платеж не выполнен",
            "payment_expired": "Платеж истек",
            "usdt": "USDT (Tether)",
            "usdc": "USDC (USD Coin)",
            "busd": "BUSD (Binance USD)",
            "dai": "DAI (Dai Stablecoin)",
            "ton": "TON (Toncoin)",
            "btc": "BTC (Bitcoin)",
            "crypto_donation_created": "Крипто-платеж успешно создан",
            "send_crypto_to_address": "Отправьте криптовалюту на указанный адрес",
            "donation_partial_success": "Платеж обработан, но возникли проблемы с сохранением данных.",
            "donation_payment_error": "Ошибка платежа",
            "donation_payment_successful": "Платеж успешен!",
            "donation_payment_processed": "Ваш платеж был успешно обработан.",
            "donation_thanks_support": "Спасибо за поддержку!",
            "donation_thanks_email": "Благодарственное письмо отправлено на ваш email.",
            "donation_warning": "Внимание",
            "donation_enter_name": "Пожалуйста, введите ваше имя",
            "donation_min_amount_error": "Минимальная сумма доната: $1",
            
            # Обратная связь
            "feedback_title": "Обратная связь",
            "feedback_description": "Сообщите нам о проблемах или предложите улучшения",
            "feedback_category_bug": "🐛 Баг",
            "feedback_category_suggestion": "💡 Предложение",
            "feedback_category_complaint": "😞 Жалоба",
            "feedback_category_other": "📝 Другое",
            "feedback_message_placeholder": "Опишите вашу проблему или предложение...",
            "attach_images": "Прикрепить фото",
            "image_hint": "Можно прикрепить до 3 фото (макс. 5MB каждое)",
            "send_feedback": "Отправить",
            "contact_admin": "Написать админу",
            "feedback_error_category": "Пожалуйста, выберите категорию",
            "feedback_error_short": "Сообщение должно содержать минимум 3 символа",
            "feedback_sending": "Отправка...",
            "feedback_success": "Спасибо! Ваше сообщение отправлено",
            "feedback_error": "Ошибка отправки",
            "feedback_network_error": "Ошибка сети",
            "admin_contact_unavailable": "Контакт админа недоступен",
            
            # Админ-панель
            "admin_analytics_title": "Админ-панель",
            "admin_analytics_subtitle": "Ключевые метрики мини-приложения",
            "access_denied_title": "Доступ запрещен",
            "access_denied_message": "Эта страница доступна только администраторам",
            "donations_title": "💰 Донаты",
            "total_donations": "Всего донатов",
            "total_amount": "Общая сумма",
            "monthly_donations": "За месяц",
            "monthly_amount": "Сумма за месяц",
            "by_source": "По источникам",
            "source_website": "Сайт",
            "source_mini_app": "Мини-апп",
            "count": "Количество",
            "amount": "Сумма",
            "subscriptions_title": "👥 Подписчики",
            "total_users": "Всего пользователей",
            "monthly_new_users": "Новых за месяц",
            "weekly_new_users": "Новых за неделю",
            "activity_title": "📊 Активность",
            "active_7_days": "Активных за 7 дней",
            "active_30_days": "Активных за 30 дней",
            "online_now": "Онлайн сейчас",
            "last_updated": "Обновлено:",
            "analytics_load_error": "Ошибка загрузки статистики",
            "admin_panel": "Админ-панель",
            
            # Общие
            "loading": "Загрузка...",
            "error": "Ошибка",
            "success": "Успешно",
            "confirm": "Подтвердить",
            "delete": "Удалить",
            "edit": "Редактировать",
            "close": "Закрыть",
            "no_tasks_for_level": "Нет задач выбранного уровня",
            
            # Профиль - дополнительные
            "points": "Баллов",
            "rating": "Рейтинг",
            "quizzes": "Квизов",
            "success_rate": "Успешность",
            "social_networks": "Социальные сети",
            "no_social_links": "Социальные сети не указаны.",
            "refresh_data": "Обновить данные",
            "refreshing_data": "Обновление данных...",
            "no_statistics_data": "Пока нет данных для отображения",
            "profile_hidden": "Профиль скрыт",
            "profile_hidden_message": "Этот пользователь скрыл свой профиль",
            "write_message": "Написать",
            "viewing_profile": "Просмотр профиля",
            "profile_visibility": "Видимость профиля",
            "public_profile": "Публичный профиль",
            "private_profile": "Скрытый профиль",
            "profile_visibility_description": "Когда включено, другие пользователи могут просматривать информацию вашего профиля",
            
            # Профессиональная информация
            "professional_info": "Профессиональная информация",
            "grade": "Грейд",
            "technologies": "Технологии",
            "grade_junior": "Junior",
            "grade_middle": "Middle",
            "grade_senior": "Senior",
            "not_specified": "Не указан",
            "no_technologies": "Технологии не указаны",
            "select_grade": "Выберите грейд",
            "select_gender": "Выберите пол",
            "loading_technologies": "Загрузка технологий...",
            
            # Персональная информация
            "years_old": "лет",
            "age_unknown": "Возраст не указан",
            "grade_unknown": "Грейд не указан",
            "junior": "Junior",
            "middle": "Middle",
            "senior": "Senior",
            "birth_date": "Дата рождения",
            "gender_unknown": "Не указан",
        "website": "Веб-сайт",
        "telegram": "Telegram",
        "github": "GitHub",
        "linkedin": "LinkedIn",
        "instagram": "Instagram",
        "facebook": "Facebook",
        "youtube": "YouTube",
        "select_technologies_optional": "Выберите технологии (необязательно)",
        "selected_technologies": "Выбрано:",
        "technologies": "технологий",
        "clear_all": "Очистить все",
        "select_all": "Выбрать все",
        "technologies_help": "Нажмите на список, чтобы выбрать несколько технологий. Поле можно оставить пустым.",
        "share_topic": "Поделиться темой",
        "share_link_copied": "Ссылка для шаринга скопирована!",
        "share_topic_with_friends": "Поделитесь этой темой с друзьями!",
        }
    }
    
    def __init__(self, default_language: str = None):
        self.default_language = default_language or settings.DEFAULT_LANGUAGE
        self.current_language = self.default_language
    
    def set_language(self, language: str) -> bool:
        """Устанавливает текущий язык"""
        if language in settings.SUPPORTED_LANGUAGES:
            self.current_language = language
            return True
        return False
    
    def get_language(self) -> str:
        """Возвращает текущий язык"""
        return self.current_language
    
    def get_text(self, key: str, language: str = None) -> str:
        """Получает перевод по ключу"""
        lang = language or self.current_language
        translations = self.TRANSLATIONS.get(lang, self.TRANSLATIONS[settings.DEFAULT_LANGUAGE])
        return translations.get(key, key)
    
    def get_all_texts(self, language: str = None) -> Dict[str, str]:
        """Возвращает все переводы для указанного языка"""
        lang = language or self.current_language
        return self.TRANSLATIONS.get(lang, self.TRANSLATIONS[settings.DEFAULT_LANGUAGE])
    
    def get_supported_languages(self) -> list:
        """Возвращает список поддерживаемых языков"""
        return settings.SUPPORTED_LANGUAGES

# Создаем глобальный экземпляр сервиса локализации
localization_service = LocalizationService() 