# Generated by Django 5.1.11 on 2026-04-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text='Email для получения сообщений из формы "Свяжитесь со мной". Если пусто — письма не отправляются.',
                max_length=254,
            ),
        ),
    ]
