# Generated by Django 5.1.4 on 2025-06-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', 'add_indexes_again'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='task_filter_idx',
        ),
        migrations.RemoveIndex(
            model_name='tasktranslation',
            name='task_trans_task_lang_idx',
        ),
    ]
