# Generated by Django 5.1.4 on 2025-01-30 23:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatistics',
            name='last_attempt_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 1, 30, 23, 37, 43, 835066, tzinfo=datetime.timezone.utc), help_text='Дата последней попытки'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='taskstatistics',
            unique_together={('user', 'task')},
        ),
    ]
