# Generated by Django 5.1.4 on 2025-08-24 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAppTaskStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attempts', models.IntegerField(default=0, help_text='Количество попыток')),
                ('successful', models.BooleanField(default=False, help_text='Успешно ли решена задача')),
                ('last_attempt_date', models.DateTimeField(auto_now=True, help_text='Дата последней попытки')),
                ('selected_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('linked_statistics', models.OneToOneField(blank=True, help_text='Связь с основной статистикой после объединения пользователей', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_app_statistics_link', to='tasks.taskstatistics')),
                ('mini_app_user', models.ForeignKey(help_text='Пользователь Mini App', on_delete=django.db.models.deletion.CASCADE, related_name='task_statistics', to='accounts.miniappuser')),
                ('task', models.ForeignKey(help_text='Задача', on_delete=django.db.models.deletion.CASCADE, related_name='mini_app_statistics', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Статистика Mini App',
                'verbose_name_plural': 'Статистика Mini App',
                'db_table': 'mini_app_task_statistics',
                'indexes': [models.Index(fields=['last_attempt_date'], name='mini_app_ta_last_at_b1c727_idx')],
                'unique_together': {('mini_app_user', 'task')},
            },
        ),
    ]
