# Generated by Django 5.1.4 on 2025-05-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatistics',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
