# Generated by Django 5.1.11 on 2025-11-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_socialmediapost"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="socialmediapost",
            new_name="social_medi_task_id_40aa74_idx",
            old_name="social_medi_task_id_8f4c5a_idx",
        ),
        migrations.RenameIndex(
            model_name="socialmediapost",
            new_name="social_medi_status_e840ca_idx",
            old_name="social_medi_status_7a2b9c_idx",
        ),
        migrations.RenameIndex(
            model_name="socialmediapost",
            new_name="social_medi_created_6ace91_idx",
            old_name="social_medi_created_4d8e1f_idx",
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
