# Generated by Django 5.1.11 on 2025-12-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tasks",
            "0005_rename_social_medi_task_id_8f4c5a_idx_social_medi_task_id_40aa74_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="custom_webhook_links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Кастомные ссылки для вебхуков (JSON-массив строк)",
            ),
        ),
    ]
