# Generated by Django 5.1.11 on 2025-12-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_task_custom_webhook_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="custom_webhook_links",
        ),
    ]
