# Generated by Django 5.1 on 2025-12-01 02:45

from django.db import migrations
from django.conf import settings

def prepend_domain_to_image_urls(apps, schema_editor):
    """
    Добавляет домен S3 к тем image_url, где его нет.
    """
    Task = apps.get_model('tasks', 'Task')
    
    # Получаем домен из настроек
    # Мы не можем импортировать Django settings напрямую в миграции,
    # поэтому используем os.getenv, как в settings.py
    import os
    bucket_name = os.getenv('S3_BUCKET_NAME')
    region = os.getenv('S3_REGION', 'us-east-1')
    
    # Собираем стандартный домен
    s3_custom_domain = f'{bucket_name}.s3.{region}.amazonaws.com'
    # Проверяем, есть ли кастомный публичный домен
    domain = os.getenv('AWS_PUBLIC_MEDIA_DOMAIN', s3_custom_domain)

    if not domain:
        print("S3 domain is not configured, skipping migration.")
        return

    # Обновляем только те задачи, у которых image_url не является полным URL
    tasks_to_update = Task.objects.filter(image_url__isnull=False).exclude(image_url__startswith='http')
    
    for task in tasks_to_update:
        task.image_url = f"https://{domain}/{task.image_url}"
        task.save(update_fields=['image_url'])

def noop(apps, schema_editor):
    # Обратная миграция не требуется, т.к. мы исправляем данные
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_custom_webhook_links'),
    ]

    operations = [
        migrations.RunPython(prepend_domain_to_image_urls, noop),
    ]
