# Generated by Django 5.1.11 on 2025-12-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_fix_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, help_text="Описание задачи (из JSON)", null=True
            ),
        ),
    ]
