# Generated by Django 5.1.11 on 2025-12-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео задачи (для будущей генерации видео)",
                max_length=255,
                null=True,
            ),
        ),
    ]
