# Generated by Django 5.1.11 on 2025-12-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_add_video_url_to_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="video_generation_logs",
            field=models.TextField(
                blank=True,
                help_text="Логи процесса генерации видео (обновляется автоматически)",
                null=True,
            ),
        ),
    ]
