# Generated by Django 5.1.11 on 2025-12-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_update_social_media_post_platforms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediapost",
            name="method",
            field=models.CharField(
                choices=[("api", "Прямое API"), ("webhook", "Webhook")],
                default="api",
                help_text="Метод публикации (API или webhook)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("pinterest", "Pinterest"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("yandex_dzen", "Яндекс Дзен"),
                    ("youtube_shorts", "YouTube Shorts"),
                    ("facebook", "Facebook"),
                ],
                help_text="Платформа социальной сети",
                max_length=50,
            ),
        ),
    ]
