# Generated by Django 5.1.11 on 2025-12-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_alter_socialmediapost_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="video_urls",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='URL видео по языкам: {"ru": "url1", "en": "url2"}',
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео задачи (для совместимости, основное видео)",
                max_length=255,
                null=True,
            ),
        ),
    ]
