# Generated by Django 5.1.11 on 2025-12-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_add_video_urls_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="video_generation_progress",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Прогресс генерации видео: {"ru": true, "en": false}',
            ),
        ),
    ]
