# Generated by Django 5.1.11 on 2025-12-29 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_add_backgroundmusic"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="backgroundmusic",
            new_name="background__is_acti_c19adf_idx",
            old_name="tasks_bgmusic_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="backgroundmusic",
            new_name="background__name_91fc4e_idx",
            old_name="tasks_bgmusic_name_idx",
        ),
        migrations.AlterField(
            model_name="backgroundmusic",
            name="audio_file",
            field=models.FileField(
                help_text="Аудиофайл (поддерживается: mp3, wav, m4a, aac, ogg, flac)",
                upload_to="background_music/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "wav", "m4a", "aac", "ogg", "flac"]
                    )
                ],
            ),
        ),
    ]
