# Generated by Django 5.1.11 on 2025-12-29 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tasks",
            "0017_rename_tasks_bgmusic_is_active_idx_background__is_acti_c19adf_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="background_music",
            field=models.ForeignKey(
                blank=True,
                help_text="Выбрать фоновую музыку для этой задачи (переопределяет автоматический выбор)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.backgroundmusic",
            ),
        ),
    ]
