# Generated by Django 5.1.11 on 2025-12-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_task_background_music"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktranslation",
            name="long_explanation",
            field=models.TextField(
                blank=True,
                help_text="Подробное пошаговое объяснение для сайта",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tasktranslation",
            name="explanation",
            field=models.TextField(
                help_text="Объяснение ответа (короткое, до 200 символов для Telegram)",
                null=True,
            ),
        ),
    ]
