# Generated by Django 5.1.11 on 2026-01-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_tasktranslation_long_explanation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="video_question_texts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Кастомный текст вопроса для видео по языкам: {"ru": "Ваш текст", "en": "Your text"}. Если не указан, используется дефолтный текст.',
                null=True,
            ),
        ),
    ]
