# Generated by Django 5.1.11 on 2026-04-12 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_task_video_question_texts"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Тенант, которому принадлежит эта задача",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
    ]
