# Generated by Django 5.1.11 on 2026-04-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0023_add_platform_publication_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktranslation",
            name="source_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на источник объяснения",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tasktranslation",
            name="source_name",
            field=models.CharField(
                blank=True,
                help_text="Название источника объяснения (например, Wikipedia)",
                max_length=255,
                null=True,
            ),
        ),
    ]
