# Generated by Django 5.1.11 on 2026-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0024_tasktranslation_source_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktranslation",
            name="source_link",
            field=models.TextField(
                blank=True,
                help_text='Ссылка(и) на источник объяснения. Для нескольких ссылок используйте разделитель ";"',
                null=True,
            ),
        ),
    ]
