# Generated by Django 5.1.4 on 2025-06-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD ($)'), ('eur', 'EUR (€)'), ('rub', 'RUB (₽)')], default='usd', max_length=3, verbose_name='Currency'),
        ),
    ]
