# Generated by Django 5.1.11 on 2025-10-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="source",
            field=models.CharField(
                choices=[("website", "Website"), ("mini_app", "Mini App")],
                default="website",
                max_length=20,
                verbose_name="Source",
            ),
        ),
    ]
