# Generated by Django 5.1.11 on 2025-10-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0002_donation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="coingate_order_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="CoinGate Order ID",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="coingate_status",
            field=models.CharField(
                blank=True,
                help_text="new, pending, confirming, paid, invalid, expired, canceled",
                max_length=50,
                null=True,
                verbose_name="CoinGate Status",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="crypto_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Crypto Amount",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="crypto_currency",
            field=models.CharField(
                blank=True,
                help_text="USDT, USDC, BUSD, DAI",
                max_length=10,
                null=True,
                verbose_name="Crypto Currency",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="crypto_payment_address",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Crypto Payment Address",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="crypto_transaction_hash",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Transaction Hash"
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="payment_type",
            field=models.CharField(
                choices=[("fiat", "Fiat (Card)"), ("crypto", "Cryptocurrency")],
                default="fiat",
                max_length=10,
                verbose_name="Payment Type",
            ),
        ),
    ]
