# Generated by Django 5.1.11 on 2025-10-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donation",
            "0003_donation_coingate_order_id_donation_coingate_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="wallet_pay_order_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Wallet Pay Order ID",
            ),
        ),
    ]
