# Generated by Django 5.1.11 on 2025-10-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0004_donation_wallet_pay_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="stars_amount",
            field=models.IntegerField(
                blank=True,
                help_text="Amount in Telegram Stars (XTR)",
                null=True,
                verbose_name="Stars Amount",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="telegram_invoice_payload",
            field=models.CharField(
                blank=True,
                help_text="Custom payload for invoice identification",
                max_length=255,
                null=True,
                verbose_name="Invoice Payload",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="telegram_payment_charge_id",
            field=models.CharField(
                blank=True,
                help_text="Telegram Stars payment charge ID",
                max_length=255,
                null=True,
                verbose_name="Telegram Payment Charge ID",
            ),
        ),
    ]
