"""Make message_id nullable in tasks

Revision ID: 141b59d7f884
Revises: b9d4e762eb24
Create Date: 2024-11-18 03:41:36.918534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141b59d7f884'
down_revision: Union[str, None] = 'b9d4e762eb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
