"""Add error field to Task

Revision ID: 28e5a84f797b
Revises: 0f2e8226dd84
Create Date: 2024-10-16 00:15:56.733304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e5a84f797b'
down_revision: Union[str, None] = '0f2e8226dd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('error', sa.Boolean(), nullable=True))
    op.alter_column('tasks', 'translation_group_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'translation_group_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('tasks', 'error')
    # ### end Alembic commands ###
