"""Update models and fix relationships

Revision ID: 5f49e26264b8
Revises: 9cf0d09a9f9d
Create Date: 2024-10-13 00:19:46.852307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f49e26264b8'
down_revision: Union[str, None] = '9cf0d09a9f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
