"""Добавил поле deactivated_at в таблицу users

Revision ID: 62bd4c20df00
Revises: dcff0cfa0872
Create Date: 2024-12-25 10:21:15.347040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bd4c20df00'
down_revision: Union[str, None] = 'dcff0cfa0872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivated_at')
    # ### end Alembic commands ###
