"""Add default_links table

Revision ID: 7fa163a7b9c5
Revises: 74eb2ec9f96a
Create Date: 2024-12-12 22:16:41.430967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa163a7b9c5'
down_revision: Union[str, None] = '74eb2ec9f96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'topic', name='uix_language_topic')
    )
    op.create_index(op.f('ix_default_links_id'), 'default_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_default_links_id'), table_name='default_links')
    op.drop_table('default_links')
    # ### end Alembic commands ###
