"""Добавление TaskPoll и связи с TaskTranslation

Revision ID: 85e21761ef0c
Revises: 7fa163a7b9c5
Create Date: 2024-12-25 01:25:09.541068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e21761ef0c'
down_revision: Union[str, None] = '7fa163a7b9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_polls', sa.Column('translation_id', sa.Integer(), nullable=False))
    op.alter_column('task_polls', 'poll_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('task_polls_task_id_key', 'task_polls', type_='unique')
    op.create_unique_constraint(None, 'task_polls', ['poll_id'])
    op.create_foreign_key(None, 'task_polls', 'task_translations', ['translation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_polls', type_='foreignkey')
    op.drop_constraint(None, 'task_polls', type_='unique')
    op.create_unique_constraint('task_polls_task_id_key', 'task_polls', ['task_id'])
    op.alter_column('task_polls', 'poll_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('task_polls', 'translation_id')
    # ### end Alembic commands ###
