"""Таблица main_fallback_links для ссылки по умолчанию

Revision ID: 86160cb84d6a
Revises: 132725c56aeb
Create Date: 2024-12-28 07:22:40.756514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86160cb84d6a'
down_revision: Union[str, None] = '132725c56aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_fallback_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main_fallback_links_id'), 'main_fallback_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_fallback_links_id'), table_name='main_fallback_links')
    op.drop_table('main_fallback_links')
    # ### end Alembic commands ###
