"""Add TaskPoll model

Revision ID: 8cbf07976843
Revises: 9e99b25a727a
Create Date: 2024-11-02 04:41:40.080735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbf07976843'
down_revision: Union[str, None] = '9e99b25a727a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=True),
    sa.Column('poll_question', sa.String(), nullable=True),
    sa.Column('poll_options', sa.JSON(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('poll_type', sa.String(), nullable=True),
    sa.Column('allows_multiple_answers', sa.Boolean(), nullable=True),
    sa.Column('total_voter_count', sa.Integer(), nullable=True),
    sa.Column('poll_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_polls')
    # ### end Alembic commands ###
