"""Sync Task and Topic models

Revision ID: 9cf0d09a9f9d
Revises: 785ff3b4f18e
Create Date: 2024-10-13 00:16:52.559421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf0d09a9f9d'
down_revision: Union[str, None] = '785ff3b4f18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
