"""Add location_type to groups

Revision ID: 9e99b25a727a
Revises: feb787ac1182
Create Date: 2024-10-27 14:55:13.589391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e99b25a727a'
down_revision: Union[str, None] = 'feb787ac1182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('location_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'location_type')
    # ### end Alembic commands ###
