"""Добавление языка в MainFallbackLink

Revision ID: a353d755fe44
Revises: 86160cb84d6a
Create Date: 2024-12-28 07:58:20.884678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a353d755fe44'
down_revision: Union[str, None] = '86160cb84d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_fallback_links', sa.Column('language', sa.String(), nullable=False))
    op.create_unique_constraint('uix_language', 'main_fallback_links', ['language'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_language', 'main_fallback_links', type_='unique')
    op.drop_column('main_fallback_links', 'language')
    # ### end Alembic commands ###
