"""Add username field to Group

Revision ID: b9d4e762eb24
Revises: bb91592f2497
Create Date: 2024-11-18 03:15:33.946399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d4e762eb24'
down_revision: Union[str, None] = 'bb91592f2497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('username', sa.String(), nullable=True))
    # op.create_unique_constraint(None, 'tasks', ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('groups', 'username')
    # ### end Alembic commands ###
