"""Добавлено ondelete='CASCADE' в TaskTranslation

Revision ID: d7b1480ebf13
Revises: 9bd73ab9c56a
Create Date: 2024-10-20 21:43:44.037866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b1480ebf13'
down_revision: Union[str, None] = '9bd73ab9c56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_translations_task_id_fkey', 'task_translations', type_='foreignkey')
    op.create_foreign_key(None, 'task_translations', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_translations', type_='foreignkey')
    op.create_foreign_key('task_translations_task_id_fkey', 'task_translations', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
