"""в таблице users добавил поле updated_at для статистики

Revision ID: dcff0cfa0872
Revises: 85e21761ef0c
Create Date: 2024-12-25 09:48:59.248837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcff0cfa0872'
down_revision: Union[str, None] = '85e21761ef0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admins_telegram_id_key', 'admins', type_='unique')
    op.create_index(op.f('ix_admins_telegram_id'), 'admins', ['telegram_id'], unique=True)
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    op.drop_index(op.f('ix_admins_telegram_id'), table_name='admins')
    op.create_unique_constraint('admins_telegram_id_key', 'admins', ['telegram_id'])
    # ### end Alembic commands ###
