"""add external_link to tasks

Revision ID: ec8319ff823c
Revises: 5f49e26264b8
Create Date: 2024-10-13 07:02:53.917699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8319ff823c'
down_revision: Union[str, None] = '5f49e26264b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('external_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'external_link')
    op.drop_column('tasks', 'image_url')
    # ### end Alembic commands ###
