# Dockerfile для nginx сервера (продакшен)
FROM nginx:alpine

ARG NGINX_CONF=nginx-prod.conf
COPY ${NGINX_CONF} /etc/nginx/nginx.conf

# Создаем необходимые директории
RUN mkdir -p /var/www/certbot

# Открываем порты
EXPOSE 80 443 8080

# Запускаем nginx
CMD ["nginx", "-g", "daemon off;"]
