# Dockerfile для nginx сервера (продакшен)
FROM nginx:alpine

# Копируем продакшен конфигурацию nginx
COPY nginx-prod.conf /etc/nginx/nginx.conf

# Создаем необходимые директории
RUN mkdir -p /var/www/certbot

# Открываем порты
EXPOSE 80 443 8080

# Запускаем nginx
CMD ["nginx", "-g", "daemon off;"]
