# Generated by Django 5.1.4 on 2025-05-01 18:32

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(help_text='Язык', max_length=10)),
                ('topic', models.CharField(help_text='Тема', max_length=100)),
                ('link', models.CharField(help_text='URL ссылки', max_length=255, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'verbose_name': 'Ссылка по умолчанию',
                'verbose_name_plural': 'Ссылки по умолчанию',
                'db_table': 'default_links',
                'indexes': [models.Index(fields=['language', 'topic'], name='default_lin_languag_d3a8b2_idx')],
                'unique_together': {('language', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='MainFallbackLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(help_text='Язык', max_length=10, unique=True)),
                ('link', models.CharField(help_text='URL резервной ссылки', max_length=255, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'verbose_name': 'Основная резервная ссылка',
                'verbose_name_plural': 'Основные резервные ссылки',
                'db_table': 'main_fallback_links',
                'indexes': [models.Index(fields=['language'], name='main_fallba_languag_c6da5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор вебхука', primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='URL вебхука', max_length=255, unique=True, validators=[django.core.validators.URLValidator()])),
                ('service_name', models.CharField(help_text='Название сервиса (например, make.com, Zapier)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли вебхук')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Вебхук',
                'verbose_name_plural': 'Вебхуки',
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='webhooks_created_913b65_idx'), models.Index(fields=['is_active'], name='webhooks_is_acti_7ab6f5_idx')],
            },
        ),
    ]
