# Generated by Django 5.1.11 on 2025-12-25 13:55

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalWebhookLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Название ссылки (для удобства)", max_length=100
                    ),
                ),
                ("url", models.URLField(help_text="URL ссылки", max_length=500)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Активна ли ссылка"),
                ),
            ],
            options={
                "verbose_name": "Глобальная ссылка для вебхуков",
                "verbose_name_plural": "Глобальные ссылки для вебхуков",
                "db_table": "global_webhook_links",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DefaultLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("language", models.CharField(help_text="Язык", max_length=10)),
                ("topic", models.CharField(help_text="Тема", max_length=100)),
                (
                    "link",
                    models.CharField(
                        help_text="URL ссылки",
                        max_length=255,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка по умолчанию",
                "verbose_name_plural": "Ссылки по умолчанию",
                "db_table": "default_links",
                "indexes": [
                    models.Index(
                        fields=["language", "topic"],
                        name="default_lin_languag_d3a8b2_idx",
                    )
                ],
                "unique_together": {("language", "topic")},
            },
        ),
        migrations.CreateModel(
            name="MainFallbackLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "language",
                    models.CharField(help_text="Язык", max_length=10, unique=True),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="URL резервной ссылки",
                        max_length=255,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
            ],
            options={
                "verbose_name": "Основная резервная ссылка",
                "verbose_name_plural": "Основные резервные ссылки",
                "db_table": "main_fallback_links",
                "indexes": [
                    models.Index(
                        fields=["language"], name="main_fallba_languag_c6da5e_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaCredentials",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("pinterest", "Pinterest"),
                            ("yandex_dzen", "Яндекс Дзен"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("youtube_shorts", "YouTube Shorts"),
                            ("twitter", "Twitter/X"),
                        ],
                        help_text="Платформа социальной сети",
                        max_length=50,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        help_text="Access token для API (не требуется для браузерной автоматизации)",
                        null=True,
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="Refresh token для обновления access token",
                        null=True,
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Дата истечения access token", null=True
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительные параметры (board_id для Pinterest, channel_id для Дзен и т.д.)",
                    ),
                ),
                (
                    "browser_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("playwright", "Playwright"),
                            ("selenium", "Selenium"),
                        ],
                        help_text="Тип браузера для автоматизации (playwright/selenium)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "headless_mode",
                    models.BooleanField(
                        default=True, help_text="Использовать headless режим браузера"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Активны ли учетные данные"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата последнего обновления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Учетные данные соцсети",
                "verbose_name_plural": "Учетные данные соцсетей",
                "db_table": "social_media_credentials",
                "indexes": [
                    models.Index(
                        fields=["platform"], name="social_medi_platfor_a0d883_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="social_medi_is_acti_d35f21_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Уникальный идентификатор вебхука",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="URL вебхука", max_length=255, unique=True
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="Название сервиса (например, make.com, Zapier)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "webhook_type",
                    models.CharField(
                        choices=[
                            ("social_media", "Социальные сети"),
                            ("russian_only", "Только русский язык"),
                            ("english_only", "Только английский язык"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        help_text="Тип webhook",
                        max_length=50,
                    ),
                ),
                (
                    "target_platforms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Список платформ для этого webhook (например: ["instagram", "tiktok", "youtube_shorts"])',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Активен ли вебхук"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата последнего обновления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вебхук",
                "verbose_name_plural": "Вебхуки",
                "db_table": "webhooks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="webhooks_created_913b65_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="webhooks_is_acti_7ab6f5_idx"
                    ),
                ],
            },
        ),
    ]
