# Generated by Django 5.1.4 on 2025-05-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(help_text='URL вебхука', max_length=255, unique=True),
        ),
    ]
