# Generated by Django 5.1.11 on 2025-11-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="target_platforms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Список платформ для этого webhook (например: ["instagram", "tiktok", "youtube_shorts"])',
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="webhook_type",
            field=models.CharField(
                choices=[("social_media", "Социальные сети"), ("other", "Другое")],
                default="other",
                help_text="Тип webhook",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SocialMediaCredentials",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("pinterest", "Pinterest"),
                            ("yandex_dzen", "Яндекс Дзен"),
                            ("facebook", "Facebook"),
                        ],
                        help_text="Платформа социальной сети",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("access_token", models.TextField(help_text="Access token для API")),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="Refresh token для обновления access token",
                        null=True,
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Дата истечения access token", null=True
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительные параметры (board_id для Pinterest, channel_id для Дзен и т.д.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Активны ли учетные данные"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата последнего обновления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Учетные данные соцсети",
                "verbose_name_plural": "Учетные данные соцсетей",
                "db_table": "social_media_credentials",
                "indexes": [
                    models.Index(
                        fields=["platform"], name="social_medi_platfor_a0d883_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="social_medi_is_acti_d35f21_idx"
                    ),
                ],
            },
        ),
    ]
