# Generated by Django 5.1.11 on 2025-12-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_webhook_target_platforms_webhook_webhook_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalWebhookLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Название ссылки (для удобства)", max_length=100
                    ),
                ),
                ("url", models.URLField(help_text="URL ссылки", max_length=500)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Активна ли ссылка"),
                ),
            ],
            options={
                "verbose_name": "Глобальная ссылка для вебхуков",
                "verbose_name_plural": "Глобальные ссылки для вебхуков",
                "db_table": "global_webhook_links",
                "ordering": ["name"],
            },
        ),
    ]
