# Generated by Django 5.1.11 on 2026-04-12 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("webhooks", "0002_defaultlink_tenant_globalwebhooklink_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediacredentials",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
    ]
