# Generated by Django 5.1.11 on 2025-12-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0006_add_russian_webhook_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="webhook_type",
            field=models.CharField(
                choices=[
                    ("social_media", "Социальные сети"),
                    ("russian_only", "Только русский язык"),
                    ("other", "Другое"),
                ],
                default="other",
                help_text="Тип webhook",
                max_length=50,
            ),
        ),
    ]
