# Generated by Django 5.1.4 on 2025-05-15 19:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Мета-описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Мета-ключевые слова'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Мета-описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Мета-ключевые слова'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Содержимое поста'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание проекта'),
        ),
    ]
