# Generated by Django 5.1.4 on 2025-01-31 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='is_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(limit_choices_to={'is_portfolio': True}, related_name='projects', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_portfolio': False}, on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
