# Generated by Django 5.1.4 on 2025-05-15 20:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_meta_description_post_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
