# Generated by Django 5.1.4 on 2025-07-27 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_views_count_postshare_projectshare_postlike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postshare',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VKontakte'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VKontakte'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Платформа'),
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='blog.post', verbose_name='Пост')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр поста',
                'verbose_name_plural': 'Просмотры постов',
                'indexes': [models.Index(fields=['post', 'user', 'created_at'], name='blog_postvi_post_id_fa8eb8_idx'), models.Index(fields=['post', 'ip_address', 'created_at'], name='blog_postvi_post_id_9a58fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='blog.project', verbose_name='Проект')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр проекта',
                'verbose_name_plural': 'Просмотры проектов',
                'indexes': [models.Index(fields=['project', 'user', 'created_at'], name='blog_projec_project_bb8045_idx'), models.Index(fields=['project', 'ip_address', 'created_at'], name='blog_projec_project_1697b9_idx')],
            },
        ),
    ]
