# Generated by Django 5.1.4 on 2025-06-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'verbose_name': 'Вложение сообщения', 'verbose_name_plural': 'Вложения сообщений'},
        ),
    ]
