# Generated by Django 5.1.4 on 2025-07-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_postshare_platform_alter_projectshare_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postshare',
            name='shared_url',
            field=models.URLField(blank=True, help_text='Ссылка на репост в социальной сети', max_length=500, verbose_name='URL репоста'),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='shared_url',
            field=models.URLField(blank=True, help_text='Ссылка на репост в социальной сети', max_length=500, verbose_name='URL репоста'),
        ),
    ]
