# Generated by Django 5.1.4 on 2025-01-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_category_is_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_portfolio',
            field=models.BooleanField(default=False, verbose_name='Portfolio Category'),
        ),
    ]
