# Generated by Django 5.1.4 on 2025-06-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_messageattachment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст бегущей строки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Бегущая строка',
                'verbose_name_plural': 'Бегущие строки',
            },
        ),
    ]
