# Generated by Django 5.1.4 on 2025-03-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image_remove_project_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Медиа поста', 'verbose_name_plural': 'Медиа постов'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Медиа проекта', 'verbose_name_plural': 'Медиа проектов'},
        ),
        migrations.AddField(
            model_name='postimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog/posts/videos/'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog/projects/videos/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/posts/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/projects/'),
        ),
    ]
