# Generated by Django 5.1.4 on 2025-06-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_marqueetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='marqueetext',
            name='link_target_blank',
            field=models.BooleanField(default=True, verbose_name='Открывать в новом окне'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='link_url',
            field=models.URLField(blank=True, help_text='Если указана, текст будет ссылкой', null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Тексты на разных языках. Заполняются через админку.', verbose_name='Переводы'),
        ),
        migrations.AlterField(
            model_name='marqueetext',
            name='text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Основной текст'),
        ),
    ]
