# Generated by Django 5.1.11 on 2025-10-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_postshare_user_alter_projectshare_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "contact_info_en",
                    models.CharField(
                        max_length=500, verbose_name="Контактная информация (EN)"
                    ),
                ),
                (
                    "contact_info_ru",
                    models.CharField(
                        max_length=500, verbose_name="Контактная информация (RU)"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "websites",
                    models.JSONField(
                        default=list,
                        help_text="Список ссылок",
                        verbose_name="Веб-сайты",
                    ),
                ),
                (
                    "summary_en",
                    models.TextField(verbose_name="Профессиональное резюме (EN)"),
                ),
                (
                    "summary_ru",
                    models.TextField(verbose_name="Профессиональное резюме (RU)"),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=list, help_text="Список навыков", verbose_name="Навыки"
                    ),
                ),
                (
                    "work_history",
                    models.JSONField(
                        default=list,
                        help_text="Список объектов с полями: title_en, title_ru, period_en, period_ru, company_en, company_ru, responsibilities_en, responsibilities_ru",
                        verbose_name="История работы",
                    ),
                ),
                (
                    "education",
                    models.JSONField(
                        default=list,
                        help_text="Список объектов с полями: title_en, title_ru, period_en, period_ru, institution_en, institution_ru",
                        verbose_name="Образование",
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        default=list,
                        help_text="Список объектов с полями: name_en, name_ru, level (в процентах)",
                        verbose_name="Языки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Только одно резюме может быть активным",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
    ]
