# Generated by Django 5.1.4 on 2025-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_postimage_options_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='video',
        ),
        migrations.AddField(
            model_name='postimage',
            name='media_file',
            field=models.FileField(blank=True, help_text='Загрузите видео (MP4) или анимированный GIF', null=True, upload_to='blog/posts/videos/'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='media_file',
            field=models.FileField(blank=True, help_text='Загрузите видео (MP4) или анимированный GIF', null=True, upload_to='blog/projects/videos/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите статичное изображение (JPG, PNG)', null=True, upload_to='blog/posts/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите статичное изображение (JPG, PNG)', null=True, upload_to='blog/projects/'),
        ),
    ]
