# Generated by Django 5.1.4 on 2025-06-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_marqueetext_link_target_blank_marqueetext_link_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marqueetext',
            options={},
        ),
        migrations.RemoveField(
            model_name='marqueetext',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='marqueetext',
            name='translations',
        ),
        migrations.RemoveField(
            model_name='marqueetext',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='text_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (арабский)'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='text_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (немецкий)'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (английский)'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='text_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (испанский)'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='text_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (французский)'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='text_ja',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (японский)'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (русский)'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='text_tj',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (таджикский)'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='text_tr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (турецкий)'),
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='text_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (китайский)'),
        ),
        migrations.AlterField(
            model_name='marqueetext',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='marqueetext',
            name='link_target_blank',
            field=models.BooleanField(default=False, verbose_name='Открывать ссылку в новой вкладке'),
        ),
        migrations.AlterField(
            model_name='marqueetext',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='URL ссылки'),
        ),
        migrations.AlterField(
            model_name='marqueetext',
            name='text',
            field=models.CharField(blank=True, help_text='Основной текст (используется как запасной)', max_length=255),
        ),
    ]
