# Generated by Django 5.1.11 on 2025-10-28 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=300, verbose_name="Степень (EN)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=300, verbose_name="Степень (RU)"),
                ),
                (
                    "period_en",
                    models.CharField(max_length=100, verbose_name="Период (EN)"),
                ),
                (
                    "period_ru",
                    models.CharField(max_length=100, verbose_name="Период (RU)"),
                ),
                (
                    "institution_en",
                    models.CharField(
                        max_length=500, verbose_name="Учебное заведение (EN)"
                    ),
                ),
                (
                    "institution_ru",
                    models.CharField(
                        max_length=500, verbose_name="Учебное заведение (RU)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_items",
                        to="blog.resume",
                        verbose_name="Резюме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись об образовании",
                "verbose_name_plural": "Образование",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ResumeLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=200, verbose_name="Язык (EN)")),
                ("name_ru", models.CharField(max_length=200, verbose_name="Язык (RU)")),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="От 0 до 100",
                        verbose_name="Уровень владения (%)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_skills",
                        to="blog.resume",
                        verbose_name="Резюме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Язык",
                "verbose_name_plural": "Языки",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ResumeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Навык")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_list",
                        to="blog.resume",
                        verbose_name="Резюме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ResumeWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="Ссылка")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_links",
                        to="blog.resume",
                        verbose_name="Резюме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Веб-сайт",
                "verbose_name_plural": "Веб-сайты",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ResumeWorkHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=300, verbose_name="Должность (EN)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=300, verbose_name="Должность (RU)"),
                ),
                (
                    "period_en",
                    models.CharField(max_length=100, verbose_name="Период (EN)"),
                ),
                (
                    "period_ru",
                    models.CharField(max_length=100, verbose_name="Период (RU)"),
                ),
                (
                    "company_en",
                    models.CharField(max_length=300, verbose_name="Компания (EN)"),
                ),
                (
                    "company_ru",
                    models.CharField(max_length=300, verbose_name="Компания (RU)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_history_items",
                        to="blog.resume",
                        verbose_name="Резюме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись истории работы",
                "verbose_name_plural": "История работы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ResumeResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_en", models.TextField(verbose_name="Обязанность (EN)")),
                ("text_ru", models.TextField(verbose_name="Обязанность (RU)")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "work_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="blog.resumeworkhistory",
                        verbose_name="История работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обязанность",
                "verbose_name_plural": "Обязанности",
                "ordering": ["order"],
            },
        ),
    ]
