# Generated by Django 5.1.4 on 2025-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_postimage_video_remove_projectimage_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='media_file',
        ),
        migrations.AddField(
            model_name='postimage',
            name='detail_page_media',
            field=models.FileField(blank=True, help_text='Загрузите видео (MP4) или анимированный GIF для отображения на странице подробностей поста.', null=True, upload_to='blog/posts/videos/', verbose_name='Медиа для страницы подробностей'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='main_page_image',
            field=models.ImageField(blank=True, help_text='Загрузите статичное изображение (JPG, PNG) для отображения на главной странице блога.', null=True, upload_to='blog/posts/', verbose_name='Изображение для главной страницы'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='detail_page_media',
            field=models.FileField(blank=True, help_text='Загрузите видео (MP4) или анимированный GIF для отображения на странице подробностей проекта.', null=True, upload_to='blog/projects/videos/', verbose_name='Медиа для страницы подробностей'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='main_page_image',
            field=models.ImageField(blank=True, help_text='Загрузите статичное изображение (JPG, PNG) для отображения на главной странице портфолио.', null=True, upload_to='blog/projects/', verbose_name='Изображение для главной страницы'),
        ),
    ]
