# Generated by Django 5.1.11 on 2025-10-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_resumeeducation_resumelanguage_resumeskill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="contact_info_en",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Контактная информация (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="contact_info_ru",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Контактная информация (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="summary_en",
            field=models.TextField(
                blank=True, verbose_name="Профессиональное резюме (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="summary_ru",
            field=models.TextField(
                blank=True, verbose_name="Профессиональное резюме (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeeducation",
            name="institution_en",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Учебное заведение (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeeducation",
            name="institution_ru",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Учебное заведение (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeeducation",
            name="period_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Период (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeeducation",
            name="period_ru",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Период (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeeducation",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Степень (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeeducation",
            name="title_ru",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Степень (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="resumelanguage",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Язык (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="resumelanguage",
            name="name_ru",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Язык (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeresponsibility",
            name="text_en",
            field=models.TextField(blank=True, verbose_name="Обязанность (EN)"),
        ),
        migrations.AlterField(
            model_name="resumeresponsibility",
            name="text_ru",
            field=models.TextField(blank=True, verbose_name="Обязанность (RU)"),
        ),
        migrations.AlterField(
            model_name="resumeworkhistory",
            name="company_en",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Компания (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeworkhistory",
            name="company_ru",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Компания (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeworkhistory",
            name="period_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Период (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeworkhistory",
            name="period_ru",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Период (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeworkhistory",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Должность (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="resumeworkhistory",
            name="title_ru",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Должность (RU)"
            ),
        ),
    ]
