# Generated by Django 5.1.4 on 2025-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_marqueetext_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marqueetext',
            options={'ordering': ['order', 'text'], 'verbose_name': 'Бегущая строка', 'verbose_name_plural': 'Бегущие строки'},
        ),
        migrations.AddField(
            model_name='marqueetext',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Число, определяющее порядок строки (меньше — выше).', verbose_name='Порядок отображения'),
        ),
    ]
