# Generated by Django 5.1.11 on 2025-11-29 01:11

from django.db import migrations, models


def set_media_type_from_existing_data(apps, schema_editor):
    """Автоматически определяет media_type для существующих записей."""
    PageVideo = apps.get_model('blog', 'PageVideo')
    
    for video in PageVideo.objects.all():
        # Приоритет: локальное видео > YouTube > GIF
        if video.video_file:
            video.media_type = 'video_file'
        elif video.video_url:
            video.media_type = 'video_url'
        elif video.gif:
            video.media_type = 'gif'
        else:
            # Если нет медиа, ставим дефолт
            video.media_type = 'video_url'
        video.save()


def reverse_set_media_type(apps, schema_editor):
    """Обратная миграция - ничего не делаем, поле просто удалится."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_make_resume_fields_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevideo",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("video_url", "YouTube видео"),
                    ("video_file", "Локальное видео"),
                    ("gif", "GIF-файл"),
                ],
                default="video_url",
                help_text="Выберите, какое медиа отображать.",
                max_length=10,
                verbose_name="Тип медиа",
            ),
        ),
        migrations.RunPython(set_media_type_from_existing_data, reverse_set_media_type),
        migrations.AlterField(
            model_name="pagevideo",
            name="gif",
            field=models.FileField(
                blank=True,
                help_text="Загрузите GIF-файл. Используется только если выбран тип 'GIF-файл'.",
                null=True,
                upload_to="gifs/page_videos/",
                verbose_name="GIF-файл",
            ),
        ),
        migrations.AlterField(
            model_name="pagevideo",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите локальный видеофайл (например, .mp4). Используется только если выбран тип 'Локальное видео'.",
                null=True,
                upload_to="videos/page_videos/",
                verbose_name="Локальный видеофайл",
            ),
        ),
        migrations.AlterField(
            model_name="pagevideo",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Вставьте ссылку на YouTube-видео (например, https://www.youtube.com/watch?v=xxx). Используется только если выбран тип 'YouTube видео'.",
                null=True,
                verbose_name="Ссылка на YouTube",
            ),
        ),
    ]
