# Generated by Django 5.1.4 on 2025-06-08 14:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_marqueetext_options_marqueetext_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marqueetext',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL для ссылки (например, https://example.com или tg://resolve?domain=@username)', max_length=200, validators=[blog.models.CustomURLValidator()], verbose_name='URL ссылки'),
        ),
    ]
