# Generated by Django 5.1.4 on 2025-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_postimage_image_remove_postimage_media_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='detail_page_media',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='main_page_image',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='detail_page_media',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='main_page_image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='gif',
            field=models.FileField(blank=True, help_text='Загрузите анимированный GIF для поста.', null=True, upload_to='blog/posts/gifs/', verbose_name='GIF (анимация)'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Отметьте, если это медиа будет отображаться на главной странице как миниатюра поста.', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите статичное изображение (JPG или PNG) для поста.', null=True, upload_to='blog/posts/photos/', verbose_name='Фото (JPG/PNG)'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='video',
            field=models.FileField(blank=True, help_text='Загрузите видео в формате MP4 для поста.', null=True, upload_to='blog/posts/videos/', verbose_name='Видео (MP4)'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='gif',
            field=models.FileField(blank=True, help_text='Загрузите анимированный GIF для проекта.', null=True, upload_to='blog/projects/gifs/', verbose_name='GIF (анимация)'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Отметьте, если это медиа будет отображаться на главной странице как миниатюра проекта.', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите статичное изображение (JPG или PNG) для проекта.', null=True, upload_to='blog/projects/photos/', verbose_name='Фото (JPG/PNG)'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='video',
            field=models.FileField(blank=True, help_text='Загрузите видео в формате MP4 для проекта.', null=True, upload_to='blog/projects/videos/', verbose_name='Видео (MP4)'),
        ),
    ]
