# Generated by Django 5.1.11 on 2025-11-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_add_media_type_to_pagevideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevideo",
            name="show_media",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы показывать медиа на странице.",
                verbose_name="Показывать медиа",
            ),
        ),
        migrations.AddField(
            model_name="pagevideo",
            name="show_text",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы показывать текст на странице. Можно показывать вместе с медиа.",
                verbose_name="Показывать текст",
            ),
        ),
        migrations.AddField(
            model_name="pagevideo",
            name="text_content",
            field=models.TextField(
                blank=True,
                help_text="Введите текст для отображения на странице. Если пусто, будет использован текст по умолчанию. Каждый абзац с новой строки.",
                null=True,
                verbose_name="Текстовый контент",
            ),
        ),
    ]
