# Generated by Django 5.1.4 on 2025-04-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_category_created_at_alter_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('index', 'Главная страница'), ('about', 'Страница "Обо мне"')], help_text='Выберите страницу, для которой предназначено видео.', max_length=10, verbose_name='Страница')),
                ('title', models.CharField(help_text='Название, которое будет отображаться под видео.', max_length=200, verbose_name='Название видео')),
                ('video_url', models.URLField(blank=True, help_text='Вставьте ссылку на YouTube-видео (например, https://www.youtube.com/watch?v=xxx).', null=True, verbose_name='Ссылка на YouTube')),
                ('video_file', models.FileField(blank=True, help_text='Загрузите локальный видеофайл (например, .mp4), если не используете YouTube.', null=True, upload_to='videos/page_videos/', verbose_name='Локальный видеофайл')),
                ('order', models.PositiveIntegerField(default=0, help_text='Число, определяющее порядок видео в списке (меньше — выше).', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Видео для страницы',
                'verbose_name_plural': 'Видео для страниц',
                'ordering': ['order', 'title'],
            },
        ),
    ]
