# Generated by Django 5.1.11 on 2026-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_add_display_settings_to_pagevideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevideo",
            name="mobile_gif",
            field=models.FileField(
                blank=True,
                help_text="Загрузите GIF-файл для мобильной версии. Используется только если выбран тип 'GIF-файл'.",
                null=True,
                upload_to="gifs/page_videos/mobile/",
                verbose_name="GIF-файл (мобильная версия)",
            ),
        ),
        migrations.AddField(
            model_name="pagevideo",
            name="mobile_media_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("video_url", "YouTube видео"),
                    ("video_file", "Локальное видео"),
                    ("gif", "GIF-файл"),
                ],
                help_text="Выберите тип медиа для мобильной версии. Если не указано, будет использоваться основное видео.",
                max_length=10,
                null=True,
                verbose_name="Тип медиа (мобильная версия)",
            ),
        ),
        migrations.AddField(
            model_name="pagevideo",
            name="mobile_video_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите локальный видеофайл для мобильной версии (например, .mp4). Используется только если выбран тип 'Локальное видео'.",
                null=True,
                upload_to="videos/page_videos/mobile/",
                verbose_name="Локальный видеофайл (мобильная версия)",
            ),
        ),
        migrations.AddField(
            model_name="pagevideo",
            name="mobile_video_url",
            field=models.URLField(
                blank=True,
                help_text="Вставьте ссылку на YouTube-видео для мобильной версии. Используется только если выбран тип 'YouTube видео'.",
                null=True,
                verbose_name="Ссылка на YouTube (мобильная версия)",
            ),
        ),
    ]
