# Generated by Django 5.1.11 on 2026-01-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_pagevideo_mobile_gif_pagevideo_mobile_media_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevideo",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Автоматически обновляется при каждом сохранении записи.",
                verbose_name="Дата обновления",
            ),
        ),
    ]
