# Generated by Django 5.1.4 on 2025-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_pagevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevideo',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='gifs/page_videos/', verbose_name='GIF-файл'),
        ),
    ]
