# Generated by Django 5.1.4 on 2025-07-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_marqueetext_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Текст, который будет отображаться, если изображение не загрузится. Важно для SEO.', max_length=255, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Текст, который будет отображаться, если изображение не загрузится. Важно для SEO.', max_length=255, verbose_name='Alt текст'),
        ),
    ]
