# Generated by Django 5.1.11 on 2026-01-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_pagevideo_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagevideo",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("video_url", "YouTube видео"),
                    ("video_file", "Локальное видео"),
                    ("gif", "GIF-файл"),
                ],
                help_text="Выберите тип медиа для десктопной версии. Если не указано, будет показываться только текст.",
                max_length=10,
                null=True,
                verbose_name="Тип медиа (десктоп)",
            ),
        ),
    ]
