# Generated by Django 5.1.11 on 2026-01-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_pagevideo_media_type"),
        ("platforms", "0001_initial"),
    ]

    operations = [
        # Разделяем состояние модели и базы данных
        migrations.SeparateDatabaseAndState(
            # Обновляем состояние модели Django
            state_operations=[
        migrations.AddField(
            model_name="post",
            name="telegram_channels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите каналы/группы для автоматической отправки поста при публикации",
                to="platforms.telegramgroup",
                verbose_name="Telegram каналы/группы",
            ),
                ),
            ],
            # Обновляем базу данных только если таблицы нет
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.tables 
                                WHERE table_name = 'blog_post_telegram_channels'
                            ) THEN
                                CREATE TABLE blog_post_telegram_channels (
                                    id BIGSERIAL PRIMARY KEY,
                                    post_id BIGINT NOT NULL REFERENCES blog_post(id) ON DELETE CASCADE,
                                    telegramgroup_id INTEGER NOT NULL REFERENCES telegram_groups(id) ON DELETE CASCADE,
                                    UNIQUE(post_id, telegramgroup_id)
                                );
                                CREATE INDEX blog_post_telegram_channels_post_id_idx 
                                ON blog_post_telegram_channels(post_id);
                                CREATE INDEX blog_post_telegram_channels_telegramgroup_id_idx 
                                ON blog_post_telegram_channels(telegramgroup_id);
                            END IF;
                        END $$;
                    """,
                    reverse_sql="DROP TABLE IF EXISTS blog_post_telegram_channels;",
                ),
            ],
        ),
    ]
