# Generated by Django 5.1.11 on 2026-01-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_post_telegram_channels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postshare",
            name="platform",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("vk", "VKontakte"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("linkedin", "LinkedIn"),
                    ("whatsapp", "WhatsApp"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("pinterest", "Pinterest"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=50,
                verbose_name="Платформа",
            ),
        ),
        migrations.AlterField(
            model_name="projectshare",
            name="platform",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("vk", "VKontakte"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("linkedin", "LinkedIn"),
                    ("whatsapp", "WhatsApp"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("pinterest", "Pinterest"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=50,
                verbose_name="Платформа",
            ),
        ),
    ]
