# Generated by Django 5.1.11 on 2026-01-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_postshare_platform_alter_projectshare_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="TinyMCEUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="tinymce_uploads/", verbose_name="Изображение"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="Размер файла (байт)"),
                ),
            ],
            options={
                "verbose_name": "Изображение TinyMCE",
                "verbose_name_plural": "Изображения TinyMCE",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
