# Generated by Django 5.1.11 on 2026-04-12 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_tinymceupload"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="marqueetext",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="pagevideo",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
        migrations.AddField(
            model_name="tinymceupload",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
    ]
