# Generated by Django 5.1.11 on 2026-04-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_category_tenant_marqueetext_tenant_message_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='Список объектов с полями: title_en, title_ru, period_en, period_ru, institution_en, institution_ru', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Список объектов с полями: name_en, name_ru, level (в процентах)', verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='Список навыков', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='websites',
            field=models.JSONField(blank=True, default=list, help_text='Список ссылок', verbose_name='Веб-сайты'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_history',
            field=models.JSONField(blank=True, default=list, help_text='Список объектов с полями: title_en, title_ru, period_en, period_ru, company_en, company_ru, responsibilities_en, responsibilities_ru', verbose_name='История работы'),
        ),
    ]
