# Generated by Django 5.1.11 on 2026-04-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_resume_education_alter_resume_languages_and_more'),
        ('tenants', '0002_tenant_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (EN)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Иконка (изображение)')),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Иконка (URL команды/внешняя)')),
                ('icon_svg', models.TextField(blank=True, null=True, verbose_name='SVG код иконки')),
                ('link', models.CharField(blank=True, help_text='Например: blog:quizes или /portfolio/', max_length=500, null=True, verbose_name='Ссылка (URL или slug)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Услуга/Функция',
                'verbose_name_plural': 'Услуги/Функции',
                'ordering': ['order'],
            },
        ),
    ]
