# Generated by Django 5.1.11 on 2026-04-12 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_service'),
        ('tenants', '0002_tenant_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя (EN)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Профессия/Заголовок (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Профессия/Заголовок (EN)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('birthday_ru', models.CharField(blank=True, max_length=100, verbose_name='Дата рождения (RU)')),
                ('birthday_en', models.CharField(blank=True, max_length=100, verbose_name='Дата рождения (EN)')),
                ('location_ru', models.CharField(blank=True, max_length=255, verbose_name='Местоположение (RU)')),
                ('location_en', models.CharField(blank=True, max_length=255, verbose_name='Местоположение (EN)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram (@username или ссылка)')),
                ('github', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Данные владельца',
                'verbose_name_plural': 'Данные владельца',
            },
        ),
    ]
