# Generated by Django 5.1.11 on 2026-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_resumeskill_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevideo',
            name='text_content_en',
            field=models.TextField(blank=True, help_text='Введите текст на английском. Каждый абзац с новой строки.', null=True, verbose_name='Текстовый контент (EN)'),
        ),
        migrations.AddField(
            model_name='pagevideo',
            name='text_content_ru',
            field=models.TextField(blank=True, help_text='Введите текст на русском. Каждый абзац с новой строки.', null=True, verbose_name='Текстовый контент (RU)'),
        ),
        migrations.AlterField(
            model_name='pagevideo',
            name='text_content',
            field=models.TextField(blank=True, help_text='Используйте поля ниже для RU/EN контента.', null=True, verbose_name='Текстовый контент (устарело)'),
        ),
    ]
