# Generated by Django 5.1.11 on 2026-04-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_pagevideo_text_content_en_pagevideo_text_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevideo',
            name='text_content',
        ),
    ]
