# Generated by Django 5.1.11 on 2026-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_pagevideo_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='display_page',
            field=models.CharField(choices=[('all', 'Везде'), ('index', 'Главная страница (Особенности)'), ('about', 'Страница Обо мне (Услуги)')], default='about', help_text='Выберите, на какой странице показывать эту карточку.', max_length=10, verbose_name='Где отображать'),
        ),
    ]
