# Generated by Django 5.1.11 on 2026-04-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_service_display_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantinfo",
            name="tiktok",
            field=models.URLField(blank=True, verbose_name="TikTok URL"),
        ),
        migrations.AddField(
            model_name="tenantinfo",
            name="vkontakte",
            field=models.URLField(blank=True, verbose_name="VKontakte URL"),
        ),
        migrations.AddField(
            model_name="tenantinfo",
            name="yandex_zen",
            field=models.URLField(blank=True, verbose_name="Yandex Zen URL"),
        ),
        migrations.AlterField(
            model_name="service",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="Рекомендуется использовать формат 'app:name' (напр. 'blog:quizes') для авто-подстановки языка. Или путь без языка (напр. '/quizes/').",
                max_length=500,
                null=True,
                verbose_name="Ссылка (URL или slug)",
            ),
        ),
    ]
