# Generated by Django 5.1.11 on 2026-04-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_tenantinfo_tiktok_tenantinfo_vkontakte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantinfo",
            name="bio_en",
            field=models.TextField(blank=True, verbose_name="О себе (EN)"),
        ),
        migrations.AddField(
            model_name="tenantinfo",
            name="bio_ru",
            field=models.TextField(blank=True, verbose_name="О себе (RU)"),
        ),
    ]
