# Generated by Django 5.1.11 on 2026-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_tenantinfo_bio_en_tenantinfo_bio_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantinfo",
            name="about_title_en",
            field=models.CharField(
                blank=True,
                default="About me",
                max_length=200,
                null=True,
                verbose_name="Заголовок страницы Обо мне (EN)",
            ),
        ),
        migrations.AddField(
            model_name="tenantinfo",
            name="about_title_ru",
            field=models.CharField(
                blank=True,
                default="Обо мне",
                max_length=200,
                null=True,
                verbose_name="Заголовок страницы Обо мне (RU)",
            ),
        ),
    ]
