# Generated by Django 5.1.11 on 2026-04-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_tenantinfo_about_title_en_tenantinfo_about_title_ru"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantinfo",
            name="about_title_en",
        ),
        migrations.RemoveField(
            model_name="tenantinfo",
            name="about_title_ru",
        ),
    ]
