# Generated by Django 5.1.11 on 2026-04-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_remove_tenantinfo_about_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantinfo",
            name="whatsapp",
            field=models.URLField(
                blank=True, verbose_name="WhatsApp URL (номер или ссылка)"
            ),
        ),
    ]
