# Generated by Django 5.1.11 on 2026-04-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_tenantinfo_whatsapp"),
        ("tenants", "0002_tenant_contact_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=100, verbose_name="Название (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=100, verbose_name="Название (EN)"),
                ),
                ("url", models.URLField(verbose_name="Ссылка URL")),
                (
                    "icon_svg",
                    models.TextField(blank=True, verbose_name="SVG код иконки"),
                ),
                (
                    "icon_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="resources/",
                        verbose_name="Иконка (файл)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources_list",
                        to="tenants.tenant",
                        verbose_name="Тенант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресурс платформы",
                "verbose_name_plural": "Ресурсы платформы",
                "ordering": ["order", "title_ru"],
            },
        ),
    ]
