# Generated by Django 5.1.11 on 2026-04-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0030_platformresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformresource",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Описание (EN)"
            ),
        ),
        migrations.AddField(
            model_name="platformresource",
            name="description_ru",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Описание (RU)"
            ),
        ),
    ]
