# Generated by Django 5.1.11 on 2026-04-26 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0032_globalchatban_globalchatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalchatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="blog.globalchatmessage",
                verbose_name="Ответ на сообщение",
            ),
        ),
    ]
