# Generated by Django 5.1.4 on 2025-04-27 21:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(help_text='Telegram ID пользователя')),
                ('username', models.CharField(help_text='Имя пользователя в Telegram', max_length=255, null=True)),
                ('message', models.TextField(help_text='Текст сообщения обратной связи', validators=[django.core.validators.MinLengthValidator(3)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время создания сообщения')),
                ('is_processed', models.BooleanField(default=False, help_text='Статус обработки сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'db_table': 'feedback_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='feedback_me_created_6ddecb_idx'), models.Index(fields=['is_processed'], name='feedback_me_is_proc_600209_idx')],
            },
        ),
    ]
