# Generated by Django 5.1.4 on 2025-07-19 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreply',
            name='admin_telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram ID администратора, который дал ответ', null=True, verbose_name='Telegram ID администратора'),
        ),
        migrations.AddField(
            model_name='feedbackreply',
            name='admin_username',
            field=models.CharField(blank=True, help_text='Имя пользователя администратора в Telegram', max_length=255, null=True, verbose_name='Имя администратора в Telegram'),
        ),
        migrations.AlterField(
            model_name='feedbackreply',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Администратор, который дал ответ', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
    ]
