# Generated by Django 5.1.11 on 2025-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_feedbackreply_admin_telegram_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackmessage",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bug", "Bug"),
                    ("suggestion", "Suggestion"),
                    ("complaint", "Complaint"),
                    ("other", "Other"),
                ],
                help_text="Категория обратной связи",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedbackmessage",
            name="source",
            field=models.CharField(
                choices=[("bot", "Telegram Bot"), ("mini_app", "Mini App")],
                default="bot",
                help_text="Источник сообщения (бот или мини-апп)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackmessage",
            index=models.Index(fields=["source"], name="feedback_me_source_5b516c_idx"),
        ),
        migrations.AddIndex(
            model_name="feedbackmessage",
            index=models.Index(
                fields=["category"], name="feedback_me_categor_529004_idx"
            ),
        ),
    ]
