# Generated by Django 5.1.11 on 2025-10-27 12:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_feedbackmessage_category_feedbackmessage_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Изображение (макс. 5MB, форматы: JPEG, PNG, GIF, WebP)",
                        upload_to="feedback_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время загрузки изображения",
                        verbose_name="Дата загрузки",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        help_text="Сообщение обратной связи",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="feedback.feedbackmessage",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение к обратной связи",
                "verbose_name_plural": "Изображения к обратной связи",
                "db_table": "feedback_images",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackReplyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Изображение (макс. 5MB, форматы: JPEG, PNG, GIF, WebP)",
                        upload_to="feedback_reply_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время загрузки изображения",
                        verbose_name="Дата загрузки",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        help_text="Ответ администратора",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="feedback.feedbackreply",
                        verbose_name="Ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение к ответу админа",
                "verbose_name_plural": "Изображения к ответам админа",
                "db_table": "feedback_reply_images",
                "ordering": ["id"],
            },
        ),
    ]
