# Generated by Django 5.1.11 on 2026-04-12 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_feedbackimage_feedbackreplyimage"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackmessage",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
    ]
