# Generated by Django 5.1.4 on 2025-01-21 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Подтема',
                'verbose_name_plural': 'Подтемы',
                'db_table': 'subtopics',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=50)),
                ('published', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('translation_group_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('error', models.BooleanField(blank=True, default=False)),
                ('message_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('successful', models.BooleanField(default=False)),
                ('last_attempt_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Статистика задачи',
                'verbose_name_plural': 'Статистика задач',
                'db_table': 'task_statistics',
            },
        ),
        migrations.CreateModel(
            name='TaskTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('answers', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Перевод задачи',
                'verbose_name_plural': 'Переводы задач',
                'db_table': 'task_translations',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'topics',
            },
        ),
    ]
