# Generated by Django 5.1.4 on 2025-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(help_text='Имя группы/канала', max_length=255)),
                ('group_id', models.BigIntegerField(db_index=True, help_text='Telegram ID группы/канала', unique=True)),
                ('topic_id', models.IntegerField(help_text='ID связанной темы')),
                ('language', models.CharField(help_text='Язык группы/канала', max_length=50)),
                ('location_type', models.CharField(choices=[('group', 'Group'), ('channel', 'Channel'), ('web', 'Website')], default='group', help_text='Тип: группа, канал или веб-сайт', max_length=50)),
                ('username', models.CharField(blank=True, help_text='Username группы/канала', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Telegram канал',
                'verbose_name_plural': 'Telegram каналы',
                'db_table': 'groups',
            },
        ),
    ]
