# Generated by Django 5.1.4 on 2025-05-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(help_text='Имя группы или канала', max_length=255)),
                ('group_id', models.BigIntegerField(db_index=True, help_text='Telegram ID группы или канала', unique=True)),
                ('language', models.CharField(help_text='Язык группы или канала', max_length=50)),
                ('location_type', models.CharField(choices=[('group', 'Group'), ('channel', 'Channel'), ('web', 'Website')], default='group', help_text='Тип: группа, канал или веб-сайт', max_length=50)),
                ('username', models.CharField(blank=True, help_text='Username группы или канала', max_length=255, null=True)),
                ('topic_id', models.ForeignKey(help_text='Связанная тема', on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
            ],
            options={
                'verbose_name': 'Telegram группа/канал',
                'verbose_name_plural': 'Telegram группы/каналы',
                'db_table': 'telegram_groups',
            },
        ),
    ]
