"""
Переименование столбца topic_id_id в topic_id в таблице telegram_groups.

Generated by Django on 2025-05-05.
"""

from django.db import migrations


class Migration(migrations.Migration):
    """
    Миграция для переименования столбца topic_id_id в topic_id в таблице telegram_groups.
    """

    dependencies = [
        ('platforms', '0001_initial'),  # Замените на последнюю миграцию в platforms
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE telegram_groups RENAME COLUMN topic_id_id TO topic_id;',
            reverse_sql='ALTER TABLE telegram_groups RENAME COLUMN topic_id TO topic_id_id;'
        ),
    ]