# Generated by Django 5.1.4 on 2025-02-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='location_type',
            field=models.CharField(choices=[('group', 'Group'), ('channel', 'Channel'), ('web', 'Website')], default='group', help_text='Тип: группа, канал или веб-сайт', max_length=50),
        ),
    ]
