# Generated by Django 5.1.11 on 2026-04-12 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platforms", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Тенант, которому принадлежит эта группа/канал",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_groups",
                to="tenants.tenant",
                verbose_name="Тенант",
            ),
        ),
    ]
