# Generated by Django 5.1.4 on 2025-05-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_rename_topic_id_id_to_topic_id'),
    ]

    operations = [
    ]
