# Generated by Django 5.1.4 on 2025-05-05 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_auto_20250505_2108'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='topic_id',
            field=models.ForeignKey(db_column='topic_id', help_text='Связанная тема', on_delete=django.db.models.deletion.CASCADE, to='topics.topic'),
        ),
    ]
